/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessToken: () => import('#controllers/access_token_controller'),
  Assignments: () => import('#controllers/assignments_controller'),
  Categories: () => import('#controllers/categories_controller'),
  EventJobs: () => import('#controllers/event_jobs_controller'),
  EventProducts: () => import('#controllers/event_products_controller'),
  Events: () => import('#controllers/events_controller'),
  FastPasses: () => import('#controllers/fast_passes_controller'),
  Furnitures: () => import('#controllers/furnitures_controller'),
  Goods: () => import('#controllers/goods_controller'),
  JobEligibleMembers: () => import('#controllers/job_eligible_members_controller'),
  Jobs: () => import('#controllers/jobs_controller'),
  Logs: () => import('#controllers/logs_controller'),
  Members: () => import('#controllers/members_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Permissions: () => import('#controllers/permissions_controller'),
  Preferences: () => import('#controllers/preferences_controller'),
  Products: () => import('#controllers/products_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Responses: () => import('#controllers/responses_controller'),
  Restocks: () => import('#controllers/restocks_controller'),
  Roles: () => import('#controllers/roles_controller'),
  Sessions: () => import('#controllers/sessions_controller'),
  StockBatches: () => import('#controllers/stock_batches_controller'),
  StockMovements: () => import('#controllers/stock_movements_controller'),
  Stocks: () => import('#controllers/stocks_controller'),
  Suppliers: () => import('#controllers/suppliers_controller'),
  Transactions: () => import('#controllers/transactions_controller'),
  Vouchers: () => import('#controllers/vouchers_controller'),
}
