/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessToken: () => import('#controllers/access_token_controller'),
  Categories: () => import('#controllers/categories_controller'),
  FastPasses: () => import('#controllers/fast_passes_controller'),
  Furnitures: () => import('#controllers/furnitures_controller'),
  Goods: () => import('#controllers/goods_controller'),
  Logs: () => import('#controllers/logs_controller'),
  Members: () => import('#controllers/members_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Permissions: () => import('#controllers/permissions_controller'),
  Products: () => import('#controllers/products_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Restocks: () => import('#controllers/restocks_controller'),
  Roles: () => import('#controllers/roles_controller'),
  StockBatches: () => import('#controllers/stock_batches_controller'),
  StockMovements: () => import('#controllers/stock_movements_controller'),
  Suppliers: () => import('#controllers/suppliers_controller'),
}
