export const PERMISSIONS = [
  'presence:write',
  'presence:read',
  'stock:read',
  'stock:write',
  'stock:delete',
  'product:read',
  'product:write',
  'product:delete',
  'supplier:read',
  'supplier:write',
  'supplier:delete',
  'restock:read',
  'restock:write',
  'restock:delete',
  'log:read',
  'event:matching',
  'event:settle',
  'assignment:write',
  'assignment:delete',
  'member:read',
  'member:write',
  'member:delete',
  'role:read',
  'role:write',
  'role:delete',
  'voucher:read',
  'voucher:write',
  'voucher:delete',
  'menu:read',
  'menu:write',
  'menu:delete',
  'category:read',
  'category:write',
  'category:delete',
  'good:read',
  'good:write',
  'good:delete',
  'furniture:read',
  'furniture:write',
  'furniture:delete',
  'event:read',
  'event:write',
  'event:delete',
  'job:read',
  'job:write',
  'job:delete',
  'fast-pass:read',
  'fast-pass:write',
  'fast-pass:delete',
  'transaction:read',
] as const

export type PermissionName = (typeof PERMISSIONS)[number]

export const ROLES = [
  'President',
  'Administrateur',
  'Tresorier',
  'Coordinateur',
  'Secretaire',
  'Pole Log',
  'Pole BBQ',
  'Membre',
] as const

export type RoleName = (typeof ROLES)[number]

// Base copied into every role: a member holds a single role and nothing is
// inherited. `member:read` and `menu:read` are here because the home page of any
// ordinary member calls them — the guard is still useful, but it exists to make
// access explicit and revocable, not to restrict.
const BASE: readonly PermissionName[] = [
  'presence:read',
  'presence:write',
  'member:read',
  'menu:read',
  'event:read',
]

const SPECIFIC: Record<RoleName, readonly PermissionName[]> = {
  'President': PERMISSIONS,
  'Administrateur': PERMISSIONS,
  'Tresorier': [
    'supplier:read',
    'supplier:write',
    'supplier:delete',
    'restock:read',
    'restock:write',
    'product:read',
    'stock:read',
    'log:read',
    'voucher:read',
    'voucher:write',
    'voucher:delete',
    'fast-pass:read',
    'fast-pass:write',
    'fast-pass:delete',
    'transaction:read',
  ],
  'Coordinateur': [
    'event:matching',
    'event:settle',
    'event:write',
    'event:delete',
    'assignment:write',
    'assignment:delete',
    'stock:read',
    'menu:write',
    'menu:delete',
    'job:read',
    'job:write',
    'job:delete',
  ],
  'Secretaire': ['log:read', 'role:read'],
  'Pole Log': [
    'stock:read',
    'stock:write',
    'stock:delete',
    'product:read',
    'product:write',
    'product:delete',
    'restock:read',
    'restock:write',
    'restock:delete',
    'supplier:read',
    'voucher:read',
    'voucher:write',
    'voucher:delete',
    'menu:write',
    'menu:delete',
    'category:read',
    'category:write',
    'category:delete',
    'good:read',
    'good:write',
    'good:delete',
    'furniture:read',
    'furniture:write',
    'furniture:delete',
  ],
  'Pole BBQ': [
    'stock:read',
    'stock:write',
    'product:read',
    'restock:read',
    'restock:write',
    'good:read',
    'furniture:read',
  ],
  'Membre': [],
}

export const ROLE_PERMISSIONS = Object.fromEntries(
  ROLES.map((role): [RoleName, PermissionName[]] => [
    role,
    [...new Set([...BASE, ...SPECIFIC[role]])],
  ])
) as Record<RoleName, PermissionName[]>
