export const PERMISSIONS = [
  'presence:write',
  'presence:read',
  'stock:read',
  'stock:write',
  'stock:delete',
  'product:read',
  'product:write',
  'product:delete',
  'supplier:read',
  'supplier:write',
  'supplier:delete',
  'restock:read',
  'restock:write',
  'restock:delete',
  'log:read',
  'log:delete',
  'event:matching',
  'event:settle',
  'assignment:write',
  'assignment:delete',
  'member:read',
  'member:write',
  'member:delete',
  'role:read',
  'role:write',
  'role:delete',
  'voucher:read',
  'voucher:write',
  'voucher:delete',
  'menu:read',
  'menu:write',
  'menu:delete',
  'category:read',
  'category:write',
  'category:delete',
  'storage-location:read',
  'storage-location:write',
  'storage-location:delete',
  'good:read',
  'good:write',
  'good:delete',
  'furniture:read',
  'furniture:write',
  'furniture:delete',
  'event:read',
  'event:write',
  'event:delete',
  'job:read',
  'job:write',
  'job:delete',
  'fast-pass:read',
  'fast-pass:write',
  'fast-pass:delete',
  'transaction:read',
  'payment:read',
  'order:read',
  'order:serve',
  'order:write',
  'order:delete',
  'order:discount',
  'client:read',
  'client:write',
  'client:delete',
  'subscription:read',
  'subscription:write',
  'subscription:delete',
  'ticket:read',
  'ticket:write',
] as const

export type PermissionName = (typeof PERMISSIONS)[number]

export const ROLES = [
  'President',
  'Administrateur',
  'Tresorier',
  'Coordinateur',
  'Secretaire',
  'Pole Log',
  'Pole BBQ',
  'Membre',
] as const

export type RoleName = (typeof ROLES)[number]

// Base copied into every role: a member holds a single role and nothing is
// inherited. `member:read` and `menu:read` are here because the home page of any
// ordinary member calls them — the guard is still useful, but it exists to make
// access explicit and revocable, not to restrict.
const BASE: readonly PermissionName[] = [
  'presence:read',
  'presence:write',
  'member:read',
  'menu:read',
  'event:read',
  'order:read',
  'order:serve',
]

const SPECIFIC: Record<RoleName, readonly PermissionName[]> = {
  'President': PERMISSIONS,
  'Administrateur': PERMISSIONS,
  'Tresorier': [
    'supplier:read',
    'supplier:write',
    'supplier:delete',
    'restock:read',
    'restock:write',
    'product:read',
    'stock:read',
    'log:read',
    'voucher:read',
    'voucher:write',
    'voucher:delete',
    'fast-pass:read',
    'fast-pass:write',
    'fast-pass:delete',
    'transaction:read',
    'payment:read',
    'order:read',
    'order:write',
    'order:delete',
    // ⚠️ Consentie au Trésorier seul parmi les rôles non pleins : une remise est
    // une concession sur l'argent, et le Coordinateur qui tient le comptoir peut
    // encaisser sans pouvoir l'accorder. À élargir depuis l'écran des rôles si le
    // bureau en décide autrement — c'est un réglage, pas une règle du code.
    'order:discount',
    'client:read',
    'client:write',
    'client:delete',
    'subscription:read',
    'subscription:write',
    'subscription:delete',
  ],
  'Coordinateur': [
    'event:matching',
    'event:settle',
    'event:write',
    'event:delete',
    'assignment:write',
    'assignment:delete',
    'stock:read',
    'menu:write',
    'menu:delete',
    'job:read',
    'job:write',
    'job:delete',
    'order:read',
    'order:write',
    'order:delete',
  ],
  'Secretaire': [
    'log:read',
    'role:read',
    'client:read',
    'subscription:read',
    'ticket:read',
    'ticket:write',
  ],
  'Pole Log': [
    'stock:read',
    'stock:write',
    'stock:delete',
    'product:read',
    'product:write',
    'product:delete',
    'restock:read',
    'restock:write',
    'restock:delete',
    'supplier:read',
    'voucher:read',
    'voucher:write',
    'voucher:delete',
    'menu:write',
    'menu:delete',
    'category:read',
    'category:write',
    'category:delete',
    // Tenir les catégories de denrées et tenir leurs lieux de stockage relèvent
    // du même métier : le pôle qui range est celui qui nomme les rangements.
    'storage-location:read',
    'storage-location:write',
    'storage-location:delete',
    'good:read',
    'good:write',
    'good:delete',
    'furniture:read',
    'furniture:write',
    'furniture:delete',
    'order:read',
  ],
  // Le pôle BBQ tient la cuisine, pas le comptoir : `order:read` et
  // `order:serve` lui viennent de BASE et lui suffisent pour lire la file et la
  // faire avancer. Ni `order:write` ni `order:delete` — prendre une commande et
  // l'annuler touchent l'argent, et l'argent est un autre poste.
  'Pole BBQ': [
    'stock:read',
    'stock:write',
    'product:read',
    'restock:read',
    'restock:write',
    'good:read',
    'furniture:read',
  ],
  'Membre': [],
}

export const ROLE_PERMISSIONS = Object.fromEntries(
  ROLES.map((role): [RoleName, PermissionName[]] => [
    role,
    [...new Set([...BASE, ...SPECIFIC[role]])],
  ])
) as Record<RoleName, PermissionName[]>
