/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = [
    'abilities',
    'createdAt',
    'expiresAt',
    'hash',
    'id',
    'ipAddress',
    'lastUsedAt',
    'name',
    'tokenableId',
    'type',
    'updatedAt',
    'userAgent',
  ] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare ipAddress: string | null
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userAgent: string | null
}

export class CategorySchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'updatedAt'] as const
  $columns = CategorySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class EventJobSchema extends BaseModel {
  static $columns = ['count', 'createdAt', 'eventId', 'jobId', 'updatedAt'] as const
  $columns = EventJobSchema.$columns
  @column()
  declare count: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare eventId: number
  @column()
  declare jobId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class EventProductSchema extends BaseModel {
  static $columns = ['createdAt', 'eventId', 'price', 'productId', 'quantity', 'updatedAt'] as const
  $columns = EventProductSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare eventId: number
  @column()
  declare price: number
  @column()
  declare productId: number
  @column()
  declare quantity: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class EventSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'date',
    'description',
    'duration',
    'id',
    'name',
    'status',
    'updatedAt',
  ] as const
  $columns = EventSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare date: DateTime
  @column()
  declare description: string | null
  @column()
  declare duration: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare status: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class FastPassSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'description',
    'duration',
    'id',
    'label',
    'price',
    'updatedAt',
  ] as const
  $columns = FastPassSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare duration: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare label: string
  @column()
  declare price: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class FurnitureSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'price', 'quantity', 'updatedAt'] as const
  $columns = FurnitureSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare price: string
  @column()
  declare quantity: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class GoodSupplierSchema extends BaseModel {
  static $columns = ['createdAt', 'goodId', 'price', 'supplierId', 'updatedAt'] as const
  $columns = GoodSupplierSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare goodId: number
  @column()
  declare price: string
  @column()
  declare supplierId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class GoodSchema extends BaseModel {
  static $columns = [
    'barcode',
    'brand',
    'categoryId',
    'createdAt',
    'id',
    'name',
    'unit',
    'updatedAt',
  ] as const
  $columns = GoodSchema.$columns
  @column()
  declare barcode: string | null
  @column()
  declare brand: string
  @column()
  declare categoryId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare unit: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class JobEligibleMemberSchema extends BaseModel {
  static $columns = ['createdAt', 'jobId', 'memberId', 'updatedAt'] as const
  $columns = JobEligibleMemberSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare jobId: number
  @column()
  declare memberId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class JobSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'name', 'type', 'updatedAt'] as const
  $columns = JobSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class LogSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'id',
    'ip',
    'level',
    'message',
    'meta',
    'method',
    'url',
    'userId',
  ] as const
  $columns = LogSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare ip: string
  @column()
  declare level: string
  @column()
  declare message: string
  @column()
  declare meta: any | null
  @column()
  declare method: string
  @column()
  declare url: string
  @column()
  declare userId: number | null
}

export class MemberEventAssignedJobSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'eventId',
    'jobId',
    'locked',
    'memberId',
    'pointsDelta',
    'settledAt',
    'updatedAt',
  ] as const
  $columns = MemberEventAssignedJobSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare eventId: number
  @column()
  declare jobId: number
  @column()
  declare locked: boolean
  @column({ isPrimary: true })
  declare memberId: number
  @column()
  declare pointsDelta: number
  @column.dateTime()
  declare settledAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class MemberJobPreferenceSchema extends BaseModel {
  static $columns = ['createdAt', 'jobId', 'memberId', 'rank', 'updatedAt'] as const
  $columns = MemberJobPreferenceSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare jobId: number
  @column({ isPrimary: true })
  declare memberId: number
  @column()
  declare rank: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class MemberResponseSchema extends BaseModel {
  static $columns = ['createdAt', 'eventId', 'isAvailable', 'memberId', 'updatedAt'] as const
  $columns = MemberResponseSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare eventId: number
  @column()
  declare isAvailable: boolean
  @column({ isPrimary: true })
  declare memberId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class MemberSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'firstName',
    'id',
    'lastName',
    'points',
    'roleId',
    'updatedAt',
  ] as const
  $columns = MemberSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare firstName: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lastName: string
  @column()
  declare points: number
  @column()
  declare roleId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class OrderProductSchema extends BaseModel {
  static $columns = ['orderId', 'productId', 'quantity'] as const
  $columns = OrderProductSchema.$columns
  @column({ isPrimary: true })
  declare orderId: number
  @column()
  declare productId: number
  @column()
  declare quantity: number
}

export class OrderSchema extends BaseModel {
  static $columns = [
    'clientId',
    'createdAt',
    'eventId',
    'id',
    'memberId',
    'status',
    'transactionId',
    'updatedAt',
  ] as const
  $columns = OrderSchema.$columns
  @column()
  declare clientId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare eventId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare memberId: number | null
  @column()
  declare status: string
  @column()
  declare transactionId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PermissionSchema extends BaseModel {
  static $columns = ['createdAt', 'permission', 'updatedAt'] as const
  $columns = PermissionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare permission: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PreOrderItemSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'preOrderId',
    'productId',
    'quantity',
    'receivedQuantity',
    'updatedAt',
  ] as const
  $columns = PreOrderItemSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare preOrderId: number
  @column()
  declare productId: number
  @column()
  declare quantity: number
  @column()
  declare receivedQuantity: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PreOrderSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'eventId',
    'id',
    'pickupAt',
    'status',
    'transactionId',
    'userId',
  ] as const
  $columns = PreOrderSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare eventId: number
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare pickupAt: DateTime | null
  @column()
  declare status: string
  @column()
  declare transactionId: number | null
  @column()
  declare userId: number
}

export class ProductFurnitureSchema extends BaseModel {
  static $columns = ['createdAt', 'furnitureId', 'productId', 'quantity', 'updatedAt'] as const
  $columns = ProductFurnitureSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare furnitureId: number
  @column({ isPrimary: true })
  declare productId: number
  @column()
  declare quantity: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ProductGoodSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'goodId',
    'instruction',
    'productId',
    'quantity',
    'rank',
    'updatedAt',
  ] as const
  $columns = ProductGoodSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare goodId: number
  @column()
  declare instruction: string | null
  @column({ isPrimary: true })
  declare productId: number
  @column()
  declare quantity: number
  @column()
  declare rank: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ProductionRunSchema extends BaseModel {
  static $columns = ['createdAt', 'eventId', 'id', 'memberId', 'productId', 'quantity'] as const
  $columns = ProductionRunSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare eventId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare memberId: number | null
  @column()
  declare productId: number
  @column()
  declare quantity: number
}

export class ProductSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'description',
    'id',
    'isVegetarian',
    'name',
    'recipe',
    'updatedAt',
  ] as const
  $columns = ProductSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isVegetarian: boolean | null
  @column()
  declare name: string
  @column()
  declare recipe: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RestockSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'id',
    'memberId',
    'supplierId',
    'totalPrice',
    'updatedAt',
  ] as const
  $columns = RestockSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare memberId: number | null
  @column()
  declare supplierId: number | null
  @column()
  declare totalPrice: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RoleSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'updatedAt'] as const
  $columns = RoleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RolesPermissionSchema extends BaseModel {
  static $columns = ['createdAt', 'permissionId', 'roleId'] as const
  $columns = RolesPermissionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare permissionId: string
  @column({ isPrimary: true })
  declare roleId: number
}

export class StockBatchSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'expirationDate',
    'goodId',
    'id',
    'label',
    'quantity',
    'restockId',
    'updatedAt',
  ] as const
  $columns = StockBatchSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.date()
  declare expirationDate: DateTime | null
  @column()
  declare goodId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare label: string
  @column()
  declare quantity: string
  @column()
  declare restockId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class StockMovementSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'goodId',
    'id',
    'movementType',
    'productionRunId',
    'quantity',
    'stockBatchId',
  ] as const
  $columns = StockMovementSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare goodId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare movementType: string
  @column()
  declare productionRunId: number | null
  @column()
  declare quantity: string
  @column()
  declare stockBatchId: number
}

export class SubscriptionSchema extends BaseModel {
  static $columns = ['createdAt', 'fastPassId', 'subscribedAt', 'updatedAt', 'userId'] as const
  $columns = SubscriptionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare fastPassId: number
  @column({ isPrimary: true })
  declare subscribedAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class SupplierSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'updatedAt'] as const
  $columns = SupplierSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TransactionSchema extends BaseModel {
  static $columns = ['amount', 'createdAt', 'id', 'type', 'updatedAt'] as const
  $columns = TransactionSchema.$columns
  @column()
  declare amount: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['casId', 'createdAt', 'email', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column()
  declare casId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class VoucherSchema extends BaseModel {
  static $columns = [
    'condition',
    'createdAt',
    'expiresAt',
    'id',
    'supplierId',
    'updatedAt',
    'usedAt',
    'value',
  ] as const
  $columns = VoucherSchema.$columns
  @column()
  declare condition: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.date()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare supplierId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column.dateTime()
  declare usedAt: DateTime | null
  @column()
  declare value: string
}
