/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type MemberTransformer from '#transformers/member_transformer'
import type UserTransformer from '#transformers/user_transformer'

export namespace Data {
  export type Member = InferData<MemberTransformer>
  export namespace Member {
    export type Variants = InferVariants<MemberTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
}
