/* eslint-disable prettier/prettier */
import type { AdonisEndpoint } from '@tuyau/core/types'
import type { Registry } from './schema.d.ts'
import type { ApiDefinition } from './tree.d.ts'

const placeholder: any = {}

const routes = {
  'auth.new_account.store': {
    methods: ["POST"],
    pattern: '/v1/auth/signup',
    tokens: [{"old":"/v1/auth/signup","type":0,"val":"v1","end":""},{"old":"/v1/auth/signup","type":0,"val":"auth","end":""},{"old":"/v1/auth/signup","type":0,"val":"signup","end":""}],
    types: placeholder as Registry['auth.new_account.store']['types'],
  },
  'auth.access_token.store': {
    methods: ["POST"],
    pattern: '/v1/auth/login',
    tokens: [{"old":"/v1/auth/login","type":0,"val":"v1","end":""},{"old":"/v1/auth/login","type":0,"val":"auth","end":""},{"old":"/v1/auth/login","type":0,"val":"login","end":""}],
    types: placeholder as Registry['auth.access_token.store']['types'],
  },
  'auth.access_token.destroy': {
    methods: ["POST"],
    pattern: '/v1/auth/logout',
    tokens: [{"old":"/v1/auth/logout","type":0,"val":"v1","end":""},{"old":"/v1/auth/logout","type":0,"val":"auth","end":""},{"old":"/v1/auth/logout","type":0,"val":"logout","end":""}],
    types: placeholder as Registry['auth.access_token.destroy']['types'],
  },
  'auth.access_token.destroy_all': {
    methods: ["DELETE"],
    pattern: '/v1/auth/logout-all',
    tokens: [{"old":"/v1/auth/logout-all","type":0,"val":"v1","end":""},{"old":"/v1/auth/logout-all","type":0,"val":"auth","end":""},{"old":"/v1/auth/logout-all","type":0,"val":"logout-all","end":""}],
    types: placeholder as Registry['auth.access_token.destroy_all']['types'],
  },
  'auth.keycloak_auth.redirect': {
    methods: ["GET","HEAD"],
    pattern: '/v1/auth/keycloak/redirect',
    tokens: [{"old":"/v1/auth/keycloak/redirect","type":0,"val":"v1","end":""},{"old":"/v1/auth/keycloak/redirect","type":0,"val":"auth","end":""},{"old":"/v1/auth/keycloak/redirect","type":0,"val":"keycloak","end":""},{"old":"/v1/auth/keycloak/redirect","type":0,"val":"redirect","end":""}],
    types: placeholder as Registry['auth.keycloak_auth.redirect']['types'],
  },
  'auth.keycloak_auth.callback': {
    methods: ["GET","HEAD"],
    pattern: '/v1/auth/keycloak/callback',
    tokens: [{"old":"/v1/auth/keycloak/callback","type":0,"val":"v1","end":""},{"old":"/v1/auth/keycloak/callback","type":0,"val":"auth","end":""},{"old":"/v1/auth/keycloak/callback","type":0,"val":"keycloak","end":""},{"old":"/v1/auth/keycloak/callback","type":0,"val":"callback","end":""}],
    types: placeholder as Registry['auth.keycloak_auth.callback']['types'],
  },
  'profile.profile.show': {
    methods: ["GET","HEAD"],
    pattern: '/v1/account/profile',
    tokens: [{"old":"/v1/account/profile","type":0,"val":"v1","end":""},{"old":"/v1/account/profile","type":0,"val":"account","end":""},{"old":"/v1/account/profile","type":0,"val":"profile","end":""}],
    types: placeholder as Registry['profile.profile.show']['types'],
  },
  'profile.qrs.mine': {
    methods: ["GET","HEAD"],
    pattern: '/v1/account/qr',
    tokens: [{"old":"/v1/account/qr","type":0,"val":"v1","end":""},{"old":"/v1/account/qr","type":0,"val":"account","end":""},{"old":"/v1/account/qr","type":0,"val":"qr","end":""}],
    types: placeholder as Registry['profile.qrs.mine']['types'],
  },
  'members.index': {
    methods: ["GET","HEAD"],
    pattern: '/v1/members',
    tokens: [{"old":"/v1/members","type":0,"val":"v1","end":""},{"old":"/v1/members","type":0,"val":"members","end":""}],
    types: placeholder as Registry['members.index']['types'],
  },
  'members.store': {
    methods: ["POST"],
    pattern: '/v1/members',
    tokens: [{"old":"/v1/members","type":0,"val":"v1","end":""},{"old":"/v1/members","type":0,"val":"members","end":""}],
    types: placeholder as Registry['members.store']['types'],
  },
  'members.show': {
    methods: ["GET","HEAD"],
    pattern: '/v1/members/:id',
    tokens: [{"old":"/v1/members/:id","type":0,"val":"v1","end":""},{"old":"/v1/members/:id","type":0,"val":"members","end":""},{"old":"/v1/members/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['members.show']['types'],
  },
  'members.update': {
    methods: ["PUT","PATCH"],
    pattern: '/v1/members/:id',
    tokens: [{"old":"/v1/members/:id","type":0,"val":"v1","end":""},{"old":"/v1/members/:id","type":0,"val":"members","end":""},{"old":"/v1/members/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['members.update']['types'],
  },
  'members.destroy': {
    methods: ["DELETE"],
    pattern: '/v1/members/:id',
    tokens: [{"old":"/v1/members/:id","type":0,"val":"v1","end":""},{"old":"/v1/members/:id","type":0,"val":"members","end":""},{"old":"/v1/members/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['members.destroy']['types'],
  },
  'roles.index': {
    methods: ["GET","HEAD"],
    pattern: '/v1/roles',
    tokens: [{"old":"/v1/roles","type":0,"val":"v1","end":""},{"old":"/v1/roles","type":0,"val":"roles","end":""}],
    types: placeholder as Registry['roles.index']['types'],
  },
  'roles.store': {
    methods: ["POST"],
    pattern: '/v1/roles',
    tokens: [{"old":"/v1/roles","type":0,"val":"v1","end":""},{"old":"/v1/roles","type":0,"val":"roles","end":""}],
    types: placeholder as Registry['roles.store']['types'],
  },
  'roles.show': {
    methods: ["GET","HEAD"],
    pattern: '/v1/roles/:id',
    tokens: [{"old":"/v1/roles/:id","type":0,"val":"v1","end":""},{"old":"/v1/roles/:id","type":0,"val":"roles","end":""},{"old":"/v1/roles/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['roles.show']['types'],
  },
  'roles.update': {
    methods: ["PUT","PATCH"],
    pattern: '/v1/roles/:id',
    tokens: [{"old":"/v1/roles/:id","type":0,"val":"v1","end":""},{"old":"/v1/roles/:id","type":0,"val":"roles","end":""},{"old":"/v1/roles/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['roles.update']['types'],
  },
  'roles.destroy': {
    methods: ["DELETE"],
    pattern: '/v1/roles/:id',
    tokens: [{"old":"/v1/roles/:id","type":0,"val":"v1","end":""},{"old":"/v1/roles/:id","type":0,"val":"roles","end":""},{"old":"/v1/roles/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['roles.destroy']['types'],
  },
  'roles.sync_permissions': {
    methods: ["PUT"],
    pattern: '/v1/roles/:id/permissions',
    tokens: [{"old":"/v1/roles/:id/permissions","type":0,"val":"v1","end":""},{"old":"/v1/roles/:id/permissions","type":0,"val":"roles","end":""},{"old":"/v1/roles/:id/permissions","type":1,"val":"id","end":""},{"old":"/v1/roles/:id/permissions","type":0,"val":"permissions","end":""}],
    types: placeholder as Registry['roles.sync_permissions']['types'],
  },
  'permissions.index': {
    methods: ["GET","HEAD"],
    pattern: '/v1/permissions',
    tokens: [{"old":"/v1/permissions","type":0,"val":"v1","end":""},{"old":"/v1/permissions","type":0,"val":"permissions","end":""}],
    types: placeholder as Registry['permissions.index']['types'],
  },
  'permissions.show': {
    methods: ["GET","HEAD"],
    pattern: '/v1/permissions/:id',
    tokens: [{"old":"/v1/permissions/:id","type":0,"val":"v1","end":""},{"old":"/v1/permissions/:id","type":0,"val":"permissions","end":""},{"old":"/v1/permissions/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['permissions.show']['types'],
  },
  'categories.index': {
    methods: ["GET","HEAD"],
    pattern: '/v1/categories',
    tokens: [{"old":"/v1/categories","type":0,"val":"v1","end":""},{"old":"/v1/categories","type":0,"val":"categories","end":""}],
    types: placeholder as Registry['categories.index']['types'],
  },
  'categories.store': {
    methods: ["POST"],
    pattern: '/v1/categories',
    tokens: [{"old":"/v1/categories","type":0,"val":"v1","end":""},{"old":"/v1/categories","type":0,"val":"categories","end":""}],
    types: placeholder as Registry['categories.store']['types'],
  },
  'categories.show': {
    methods: ["GET","HEAD"],
    pattern: '/v1/categories/:id',
    tokens: [{"old":"/v1/categories/:id","type":0,"val":"v1","end":""},{"old":"/v1/categories/:id","type":0,"val":"categories","end":""},{"old":"/v1/categories/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['categories.show']['types'],
  },
  'categories.update': {
    methods: ["PUT","PATCH"],
    pattern: '/v1/categories/:id',
    tokens: [{"old":"/v1/categories/:id","type":0,"val":"v1","end":""},{"old":"/v1/categories/:id","type":0,"val":"categories","end":""},{"old":"/v1/categories/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['categories.update']['types'],
  },
  'categories.destroy': {
    methods: ["DELETE"],
    pattern: '/v1/categories/:id',
    tokens: [{"old":"/v1/categories/:id","type":0,"val":"v1","end":""},{"old":"/v1/categories/:id","type":0,"val":"categories","end":""},{"old":"/v1/categories/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['categories.destroy']['types'],
  },
  'products.summary': {
    methods: ["GET","HEAD"],
    pattern: '/v1/products/summary',
    tokens: [{"old":"/v1/products/summary","type":0,"val":"v1","end":""},{"old":"/v1/products/summary","type":0,"val":"products","end":""},{"old":"/v1/products/summary","type":0,"val":"summary","end":""}],
    types: placeholder as Registry['products.summary']['types'],
  },
  'products.ingredients': {
    methods: ["GET","HEAD"],
    pattern: '/v1/products/:id/ingredients',
    tokens: [{"old":"/v1/products/:id/ingredients","type":0,"val":"v1","end":""},{"old":"/v1/products/:id/ingredients","type":0,"val":"products","end":""},{"old":"/v1/products/:id/ingredients","type":1,"val":"id","end":""},{"old":"/v1/products/:id/ingredients","type":0,"val":"ingredients","end":""}],
    types: placeholder as Registry['products.ingredients']['types'],
  },
  'products.recipe_pdf': {
    methods: ["GET","HEAD"],
    pattern: '/v1/products/:id/recipe/pdf',
    tokens: [{"old":"/v1/products/:id/recipe/pdf","type":0,"val":"v1","end":""},{"old":"/v1/products/:id/recipe/pdf","type":0,"val":"products","end":""},{"old":"/v1/products/:id/recipe/pdf","type":1,"val":"id","end":""},{"old":"/v1/products/:id/recipe/pdf","type":0,"val":"recipe","end":""},{"old":"/v1/products/:id/recipe/pdf","type":0,"val":"pdf","end":""}],
    types: placeholder as Registry['products.recipe_pdf']['types'],
  },
  'products.index': {
    methods: ["GET","HEAD"],
    pattern: '/v1/products',
    tokens: [{"old":"/v1/products","type":0,"val":"v1","end":""},{"old":"/v1/products","type":0,"val":"products","end":""}],
    types: placeholder as Registry['products.index']['types'],
  },
  'products.store': {
    methods: ["POST"],
    pattern: '/v1/products',
    tokens: [{"old":"/v1/products","type":0,"val":"v1","end":""},{"old":"/v1/products","type":0,"val":"products","end":""}],
    types: placeholder as Registry['products.store']['types'],
  },
  'products.show': {
    methods: ["GET","HEAD"],
    pattern: '/v1/products/:id',
    tokens: [{"old":"/v1/products/:id","type":0,"val":"v1","end":""},{"old":"/v1/products/:id","type":0,"val":"products","end":""},{"old":"/v1/products/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['products.show']['types'],
  },
  'products.update': {
    methods: ["PUT","PATCH"],
    pattern: '/v1/products/:id',
    tokens: [{"old":"/v1/products/:id","type":0,"val":"v1","end":""},{"old":"/v1/products/:id","type":0,"val":"products","end":""},{"old":"/v1/products/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['products.update']['types'],
  },
  'products.destroy': {
    methods: ["DELETE"],
    pattern: '/v1/products/:id',
    tokens: [{"old":"/v1/products/:id","type":0,"val":"v1","end":""},{"old":"/v1/products/:id","type":0,"val":"products","end":""},{"old":"/v1/products/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['products.destroy']['types'],
  },
  'goods.index': {
    methods: ["GET","HEAD"],
    pattern: '/v1/goods',
    tokens: [{"old":"/v1/goods","type":0,"val":"v1","end":""},{"old":"/v1/goods","type":0,"val":"goods","end":""}],
    types: placeholder as Registry['goods.index']['types'],
  },
  'goods.store': {
    methods: ["POST"],
    pattern: '/v1/goods',
    tokens: [{"old":"/v1/goods","type":0,"val":"v1","end":""},{"old":"/v1/goods","type":0,"val":"goods","end":""}],
    types: placeholder as Registry['goods.store']['types'],
  },
  'goods.show': {
    methods: ["GET","HEAD"],
    pattern: '/v1/goods/:id',
    tokens: [{"old":"/v1/goods/:id","type":0,"val":"v1","end":""},{"old":"/v1/goods/:id","type":0,"val":"goods","end":""},{"old":"/v1/goods/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['goods.show']['types'],
  },
  'goods.update': {
    methods: ["PUT","PATCH"],
    pattern: '/v1/goods/:id',
    tokens: [{"old":"/v1/goods/:id","type":0,"val":"v1","end":""},{"old":"/v1/goods/:id","type":0,"val":"goods","end":""},{"old":"/v1/goods/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['goods.update']['types'],
  },
  'goods.destroy': {
    methods: ["DELETE"],
    pattern: '/v1/goods/:id',
    tokens: [{"old":"/v1/goods/:id","type":0,"val":"v1","end":""},{"old":"/v1/goods/:id","type":0,"val":"goods","end":""},{"old":"/v1/goods/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['goods.destroy']['types'],
  },
  'furnitures.index': {
    methods: ["GET","HEAD"],
    pattern: '/v1/furnitures',
    tokens: [{"old":"/v1/furnitures","type":0,"val":"v1","end":""},{"old":"/v1/furnitures","type":0,"val":"furnitures","end":""}],
    types: placeholder as Registry['furnitures.index']['types'],
  },
  'furnitures.store': {
    methods: ["POST"],
    pattern: '/v1/furnitures',
    tokens: [{"old":"/v1/furnitures","type":0,"val":"v1","end":""},{"old":"/v1/furnitures","type":0,"val":"furnitures","end":""}],
    types: placeholder as Registry['furnitures.store']['types'],
  },
  'furnitures.show': {
    methods: ["GET","HEAD"],
    pattern: '/v1/furnitures/:id',
    tokens: [{"old":"/v1/furnitures/:id","type":0,"val":"v1","end":""},{"old":"/v1/furnitures/:id","type":0,"val":"furnitures","end":""},{"old":"/v1/furnitures/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['furnitures.show']['types'],
  },
  'furnitures.update': {
    methods: ["PUT","PATCH"],
    pattern: '/v1/furnitures/:id',
    tokens: [{"old":"/v1/furnitures/:id","type":0,"val":"v1","end":""},{"old":"/v1/furnitures/:id","type":0,"val":"furnitures","end":""},{"old":"/v1/furnitures/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['furnitures.update']['types'],
  },
  'furnitures.destroy': {
    methods: ["DELETE"],
    pattern: '/v1/furnitures/:id',
    tokens: [{"old":"/v1/furnitures/:id","type":0,"val":"v1","end":""},{"old":"/v1/furnitures/:id","type":0,"val":"furnitures","end":""},{"old":"/v1/furnitures/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['furnitures.destroy']['types'],
  },
  'suppliers.index': {
    methods: ["GET","HEAD"],
    pattern: '/v1/suppliers',
    tokens: [{"old":"/v1/suppliers","type":0,"val":"v1","end":""},{"old":"/v1/suppliers","type":0,"val":"suppliers","end":""}],
    types: placeholder as Registry['suppliers.index']['types'],
  },
  'suppliers.store': {
    methods: ["POST"],
    pattern: '/v1/suppliers',
    tokens: [{"old":"/v1/suppliers","type":0,"val":"v1","end":""},{"old":"/v1/suppliers","type":0,"val":"suppliers","end":""}],
    types: placeholder as Registry['suppliers.store']['types'],
  },
  'suppliers.show': {
    methods: ["GET","HEAD"],
    pattern: '/v1/suppliers/:id',
    tokens: [{"old":"/v1/suppliers/:id","type":0,"val":"v1","end":""},{"old":"/v1/suppliers/:id","type":0,"val":"suppliers","end":""},{"old":"/v1/suppliers/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['suppliers.show']['types'],
  },
  'suppliers.update': {
    methods: ["PUT","PATCH"],
    pattern: '/v1/suppliers/:id',
    tokens: [{"old":"/v1/suppliers/:id","type":0,"val":"v1","end":""},{"old":"/v1/suppliers/:id","type":0,"val":"suppliers","end":""},{"old":"/v1/suppliers/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['suppliers.update']['types'],
  },
  'suppliers.destroy': {
    methods: ["DELETE"],
    pattern: '/v1/suppliers/:id',
    tokens: [{"old":"/v1/suppliers/:id","type":0,"val":"v1","end":""},{"old":"/v1/suppliers/:id","type":0,"val":"suppliers","end":""},{"old":"/v1/suppliers/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['suppliers.destroy']['types'],
  },
  'stocks.index': {
    methods: ["GET","HEAD"],
    pattern: '/v1/stocks',
    tokens: [{"old":"/v1/stocks","type":0,"val":"v1","end":""},{"old":"/v1/stocks","type":0,"val":"stocks","end":""}],
    types: placeholder as Registry['stocks.index']['types'],
  },
  'stocks.batches': {
    methods: ["GET","HEAD"],
    pattern: '/v1/stocks/:id/batches',
    tokens: [{"old":"/v1/stocks/:id/batches","type":0,"val":"v1","end":""},{"old":"/v1/stocks/:id/batches","type":0,"val":"stocks","end":""},{"old":"/v1/stocks/:id/batches","type":1,"val":"id","end":""},{"old":"/v1/stocks/:id/batches","type":0,"val":"batches","end":""}],
    types: placeholder as Registry['stocks.batches']['types'],
  },
  'stocks.discard': {
    methods: ["POST"],
    pattern: '/v1/stocks/:id/batches/:batchId/discard',
    tokens: [{"old":"/v1/stocks/:id/batches/:batchId/discard","type":0,"val":"v1","end":""},{"old":"/v1/stocks/:id/batches/:batchId/discard","type":0,"val":"stocks","end":""},{"old":"/v1/stocks/:id/batches/:batchId/discard","type":1,"val":"id","end":""},{"old":"/v1/stocks/:id/batches/:batchId/discard","type":0,"val":"batches","end":""},{"old":"/v1/stocks/:id/batches/:batchId/discard","type":1,"val":"batchId","end":""},{"old":"/v1/stocks/:id/batches/:batchId/discard","type":0,"val":"discard","end":""}],
    types: placeholder as Registry['stocks.discard']['types'],
  },
  'stock_batches.index': {
    methods: ["GET","HEAD"],
    pattern: '/v1/stock-batches',
    tokens: [{"old":"/v1/stock-batches","type":0,"val":"v1","end":""},{"old":"/v1/stock-batches","type":0,"val":"stock-batches","end":""}],
    types: placeholder as Registry['stock_batches.index']['types'],
  },
  'stock_batches.store': {
    methods: ["POST"],
    pattern: '/v1/stock-batches',
    tokens: [{"old":"/v1/stock-batches","type":0,"val":"v1","end":""},{"old":"/v1/stock-batches","type":0,"val":"stock-batches","end":""}],
    types: placeholder as Registry['stock_batches.store']['types'],
  },
  'stock_batches.inventory_pdf': {
    methods: ["GET","HEAD"],
    pattern: '/v1/stock-batches/inventory/pdf',
    tokens: [{"old":"/v1/stock-batches/inventory/pdf","type":0,"val":"v1","end":""},{"old":"/v1/stock-batches/inventory/pdf","type":0,"val":"stock-batches","end":""},{"old":"/v1/stock-batches/inventory/pdf","type":0,"val":"inventory","end":""},{"old":"/v1/stock-batches/inventory/pdf","type":0,"val":"pdf","end":""}],
    types: placeholder as Registry['stock_batches.inventory_pdf']['types'],
  },
  'stock_batches.labels_pdf': {
    methods: ["GET","HEAD"],
    pattern: '/v1/stock-batches/labels/pdf',
    tokens: [{"old":"/v1/stock-batches/labels/pdf","type":0,"val":"v1","end":""},{"old":"/v1/stock-batches/labels/pdf","type":0,"val":"stock-batches","end":""},{"old":"/v1/stock-batches/labels/pdf","type":0,"val":"labels","end":""},{"old":"/v1/stock-batches/labels/pdf","type":0,"val":"pdf","end":""}],
    types: placeholder as Registry['stock_batches.labels_pdf']['types'],
  },
  'stock_batches.show': {
    methods: ["GET","HEAD"],
    pattern: '/v1/stock-batches/:id',
    tokens: [{"old":"/v1/stock-batches/:id","type":0,"val":"v1","end":""},{"old":"/v1/stock-batches/:id","type":0,"val":"stock-batches","end":""},{"old":"/v1/stock-batches/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['stock_batches.show']['types'],
  },
  'stock_batches.update': {
    methods: ["PUT","PATCH"],
    pattern: '/v1/stock-batches/:id',
    tokens: [{"old":"/v1/stock-batches/:id","type":0,"val":"v1","end":""},{"old":"/v1/stock-batches/:id","type":0,"val":"stock-batches","end":""},{"old":"/v1/stock-batches/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['stock_batches.update']['types'],
  },
  'stock_batches.destroy': {
    methods: ["DELETE"],
    pattern: '/v1/stock-batches/:id',
    tokens: [{"old":"/v1/stock-batches/:id","type":0,"val":"v1","end":""},{"old":"/v1/stock-batches/:id","type":0,"val":"stock-batches","end":""},{"old":"/v1/stock-batches/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['stock_batches.destroy']['types'],
  },
  'stock_movements.index': {
    methods: ["GET","HEAD"],
    pattern: '/v1/stock-movements',
    tokens: [{"old":"/v1/stock-movements","type":0,"val":"v1","end":""},{"old":"/v1/stock-movements","type":0,"val":"stock-movements","end":""}],
    types: placeholder as Registry['stock_movements.index']['types'],
  },
  'stock_movements.store': {
    methods: ["POST"],
    pattern: '/v1/stock-movements',
    tokens: [{"old":"/v1/stock-movements","type":0,"val":"v1","end":""},{"old":"/v1/stock-movements","type":0,"val":"stock-movements","end":""}],
    types: placeholder as Registry['stock_movements.store']['types'],
  },
  'stock_movements.show': {
    methods: ["GET","HEAD"],
    pattern: '/v1/stock-movements/:id',
    tokens: [{"old":"/v1/stock-movements/:id","type":0,"val":"v1","end":""},{"old":"/v1/stock-movements/:id","type":0,"val":"stock-movements","end":""},{"old":"/v1/stock-movements/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['stock_movements.show']['types'],
  },
  'stock_movements.update': {
    methods: ["PUT","PATCH"],
    pattern: '/v1/stock-movements/:id',
    tokens: [{"old":"/v1/stock-movements/:id","type":0,"val":"v1","end":""},{"old":"/v1/stock-movements/:id","type":0,"val":"stock-movements","end":""},{"old":"/v1/stock-movements/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['stock_movements.update']['types'],
  },
  'stock_movements.destroy': {
    methods: ["DELETE"],
    pattern: '/v1/stock-movements/:id',
    tokens: [{"old":"/v1/stock-movements/:id","type":0,"val":"v1","end":""},{"old":"/v1/stock-movements/:id","type":0,"val":"stock-movements","end":""},{"old":"/v1/stock-movements/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['stock_movements.destroy']['types'],
  },
  'restocks.index': {
    methods: ["GET","HEAD"],
    pattern: '/v1/restocks',
    tokens: [{"old":"/v1/restocks","type":0,"val":"v1","end":""},{"old":"/v1/restocks","type":0,"val":"restocks","end":""}],
    types: placeholder as Registry['restocks.index']['types'],
  },
  'restocks.store': {
    methods: ["POST"],
    pattern: '/v1/restocks',
    tokens: [{"old":"/v1/restocks","type":0,"val":"v1","end":""},{"old":"/v1/restocks","type":0,"val":"restocks","end":""}],
    types: placeholder as Registry['restocks.store']['types'],
  },
  'restocks.show': {
    methods: ["GET","HEAD"],
    pattern: '/v1/restocks/:id',
    tokens: [{"old":"/v1/restocks/:id","type":0,"val":"v1","end":""},{"old":"/v1/restocks/:id","type":0,"val":"restocks","end":""},{"old":"/v1/restocks/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['restocks.show']['types'],
  },
  'restocks.update': {
    methods: ["PUT","PATCH"],
    pattern: '/v1/restocks/:id',
    tokens: [{"old":"/v1/restocks/:id","type":0,"val":"v1","end":""},{"old":"/v1/restocks/:id","type":0,"val":"restocks","end":""},{"old":"/v1/restocks/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['restocks.update']['types'],
  },
  'restocks.destroy': {
    methods: ["DELETE"],
    pattern: '/v1/restocks/:id',
    tokens: [{"old":"/v1/restocks/:id","type":0,"val":"v1","end":""},{"old":"/v1/restocks/:id","type":0,"val":"restocks","end":""},{"old":"/v1/restocks/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['restocks.destroy']['types'],
  },
  'events.index': {
    methods: ["GET","HEAD"],
    pattern: '/v1/events',
    tokens: [{"old":"/v1/events","type":0,"val":"v1","end":""},{"old":"/v1/events","type":0,"val":"events","end":""}],
    types: placeholder as Registry['events.index']['types'],
  },
  'events.store': {
    methods: ["POST"],
    pattern: '/v1/events',
    tokens: [{"old":"/v1/events","type":0,"val":"v1","end":""},{"old":"/v1/events","type":0,"val":"events","end":""}],
    types: placeholder as Registry['events.store']['types'],
  },
  'events.show': {
    methods: ["GET","HEAD"],
    pattern: '/v1/events/:id',
    tokens: [{"old":"/v1/events/:id","type":0,"val":"v1","end":""},{"old":"/v1/events/:id","type":0,"val":"events","end":""},{"old":"/v1/events/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['events.show']['types'],
  },
  'events.update': {
    methods: ["PUT","PATCH"],
    pattern: '/v1/events/:id',
    tokens: [{"old":"/v1/events/:id","type":0,"val":"v1","end":""},{"old":"/v1/events/:id","type":0,"val":"events","end":""},{"old":"/v1/events/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['events.update']['types'],
  },
  'events.destroy': {
    methods: ["DELETE"],
    pattern: '/v1/events/:id',
    tokens: [{"old":"/v1/events/:id","type":0,"val":"v1","end":""},{"old":"/v1/events/:id","type":0,"val":"events","end":""},{"old":"/v1/events/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['events.destroy']['types'],
  },
  'events.get_response': {
    methods: ["GET","HEAD"],
    pattern: '/v1/events/:id/response',
    tokens: [{"old":"/v1/events/:id/response","type":0,"val":"v1","end":""},{"old":"/v1/events/:id/response","type":0,"val":"events","end":""},{"old":"/v1/events/:id/response","type":1,"val":"id","end":""},{"old":"/v1/events/:id/response","type":0,"val":"response","end":""}],
    types: placeholder as Registry['events.get_response']['types'],
  },
  'events.set_response': {
    methods: ["POST"],
    pattern: '/v1/events/:id/response',
    tokens: [{"old":"/v1/events/:id/response","type":0,"val":"v1","end":""},{"old":"/v1/events/:id/response","type":0,"val":"events","end":""},{"old":"/v1/events/:id/response","type":1,"val":"id","end":""},{"old":"/v1/events/:id/response","type":0,"val":"response","end":""}],
    types: placeholder as Registry['events.set_response']['types'],
  },
  'events.roster': {
    methods: ["GET","HEAD"],
    pattern: '/v1/events/:id/roster',
    tokens: [{"old":"/v1/events/:id/roster","type":0,"val":"v1","end":""},{"old":"/v1/events/:id/roster","type":0,"val":"events","end":""},{"old":"/v1/events/:id/roster","type":1,"val":"id","end":""},{"old":"/v1/events/:id/roster","type":0,"val":"roster","end":""}],
    types: placeholder as Registry['events.roster']['types'],
  },
  'event_products.index': {
    methods: ["GET","HEAD"],
    pattern: '/v1/events/:id/products',
    tokens: [{"old":"/v1/events/:id/products","type":0,"val":"v1","end":""},{"old":"/v1/events/:id/products","type":0,"val":"events","end":""},{"old":"/v1/events/:id/products","type":1,"val":"id","end":""},{"old":"/v1/events/:id/products","type":0,"val":"products","end":""}],
    types: placeholder as Registry['event_products.index']['types'],
  },
  'event_products.store': {
    methods: ["POST"],
    pattern: '/v1/events/:id/products',
    tokens: [{"old":"/v1/events/:id/products","type":0,"val":"v1","end":""},{"old":"/v1/events/:id/products","type":0,"val":"events","end":""},{"old":"/v1/events/:id/products","type":1,"val":"id","end":""},{"old":"/v1/events/:id/products","type":0,"val":"products","end":""}],
    types: placeholder as Registry['event_products.store']['types'],
  },
  'event_products.update': {
    methods: ["PATCH"],
    pattern: '/v1/events/:id/products/:productId',
    tokens: [{"old":"/v1/events/:id/products/:productId","type":0,"val":"v1","end":""},{"old":"/v1/events/:id/products/:productId","type":0,"val":"events","end":""},{"old":"/v1/events/:id/products/:productId","type":1,"val":"id","end":""},{"old":"/v1/events/:id/products/:productId","type":0,"val":"products","end":""},{"old":"/v1/events/:id/products/:productId","type":1,"val":"productId","end":""}],
    types: placeholder as Registry['event_products.update']['types'],
  },
  'event_products.destroy': {
    methods: ["DELETE"],
    pattern: '/v1/events/:id/products/:productId',
    tokens: [{"old":"/v1/events/:id/products/:productId","type":0,"val":"v1","end":""},{"old":"/v1/events/:id/products/:productId","type":0,"val":"events","end":""},{"old":"/v1/events/:id/products/:productId","type":1,"val":"id","end":""},{"old":"/v1/events/:id/products/:productId","type":0,"val":"products","end":""},{"old":"/v1/events/:id/products/:productId","type":1,"val":"productId","end":""}],
    types: placeholder as Registry['event_products.destroy']['types'],
  },
  'event_products.shopping_list': {
    methods: ["GET","HEAD"],
    pattern: '/v1/events/:id/shopping-list',
    tokens: [{"old":"/v1/events/:id/shopping-list","type":0,"val":"v1","end":""},{"old":"/v1/events/:id/shopping-list","type":0,"val":"events","end":""},{"old":"/v1/events/:id/shopping-list","type":1,"val":"id","end":""},{"old":"/v1/events/:id/shopping-list","type":0,"val":"shopping-list","end":""}],
    types: placeholder as Registry['event_products.shopping_list']['types'],
  },
  'event_products.shopping_list_pdf': {
    methods: ["GET","HEAD"],
    pattern: '/v1/events/:id/shopping-list/pdf',
    tokens: [{"old":"/v1/events/:id/shopping-list/pdf","type":0,"val":"v1","end":""},{"old":"/v1/events/:id/shopping-list/pdf","type":0,"val":"events","end":""},{"old":"/v1/events/:id/shopping-list/pdf","type":1,"val":"id","end":""},{"old":"/v1/events/:id/shopping-list/pdf","type":0,"val":"shopping-list","end":""},{"old":"/v1/events/:id/shopping-list/pdf","type":0,"val":"pdf","end":""}],
    types: placeholder as Registry['event_products.shopping_list_pdf']['types'],
  },
  'orders.index': {
    methods: ["GET","HEAD"],
    pattern: '/v1/events/:id/orders',
    tokens: [{"old":"/v1/events/:id/orders","type":0,"val":"v1","end":""},{"old":"/v1/events/:id/orders","type":0,"val":"events","end":""},{"old":"/v1/events/:id/orders","type":1,"val":"id","end":""},{"old":"/v1/events/:id/orders","type":0,"val":"orders","end":""}],
    types: placeholder as Registry['orders.index']['types'],
  },
  'orders.store': {
    methods: ["POST"],
    pattern: '/v1/events/:id/orders',
    tokens: [{"old":"/v1/events/:id/orders","type":0,"val":"v1","end":""},{"old":"/v1/events/:id/orders","type":0,"val":"events","end":""},{"old":"/v1/events/:id/orders","type":1,"val":"id","end":""},{"old":"/v1/events/:id/orders","type":0,"val":"orders","end":""}],
    types: placeholder as Registry['orders.store']['types'],
  },
  'orders.sellable': {
    methods: ["GET","HEAD"],
    pattern: '/v1/events/:id/sellable',
    tokens: [{"old":"/v1/events/:id/sellable","type":0,"val":"v1","end":""},{"old":"/v1/events/:id/sellable","type":0,"val":"events","end":""},{"old":"/v1/events/:id/sellable","type":1,"val":"id","end":""},{"old":"/v1/events/:id/sellable","type":0,"val":"sellable","end":""}],
    types: placeholder as Registry['orders.sellable']['types'],
  },
  'orders.summary': {
    methods: ["GET","HEAD"],
    pattern: '/v1/events/:id/summary',
    tokens: [{"old":"/v1/events/:id/summary","type":0,"val":"v1","end":""},{"old":"/v1/events/:id/summary","type":0,"val":"events","end":""},{"old":"/v1/events/:id/summary","type":1,"val":"id","end":""},{"old":"/v1/events/:id/summary","type":0,"val":"summary","end":""}],
    types: placeholder as Registry['orders.summary']['types'],
  },
  'pre_orders.index': {
    methods: ["GET","HEAD"],
    pattern: '/v1/events/:id/pre-orders',
    tokens: [{"old":"/v1/events/:id/pre-orders","type":0,"val":"v1","end":""},{"old":"/v1/events/:id/pre-orders","type":0,"val":"events","end":""},{"old":"/v1/events/:id/pre-orders","type":1,"val":"id","end":""},{"old":"/v1/events/:id/pre-orders","type":0,"val":"pre-orders","end":""}],
    types: placeholder as Registry['pre_orders.index']['types'],
  },
  'production_runs.index': {
    methods: ["GET","HEAD"],
    pattern: '/v1/events/:id/production-runs',
    tokens: [{"old":"/v1/events/:id/production-runs","type":0,"val":"v1","end":""},{"old":"/v1/events/:id/production-runs","type":0,"val":"events","end":""},{"old":"/v1/events/:id/production-runs","type":1,"val":"id","end":""},{"old":"/v1/events/:id/production-runs","type":0,"val":"production-runs","end":""}],
    types: placeholder as Registry['production_runs.index']['types'],
  },
  'production_runs.store': {
    methods: ["POST"],
    pattern: '/v1/events/:id/production-runs',
    tokens: [{"old":"/v1/events/:id/production-runs","type":0,"val":"v1","end":""},{"old":"/v1/events/:id/production-runs","type":0,"val":"events","end":""},{"old":"/v1/events/:id/production-runs","type":1,"val":"id","end":""},{"old":"/v1/events/:id/production-runs","type":0,"val":"production-runs","end":""}],
    types: placeholder as Registry['production_runs.store']['types'],
  },
  'production_runs.production_plan_pdf': {
    methods: ["GET","HEAD"],
    pattern: '/v1/events/:id/production-plan/pdf',
    tokens: [{"old":"/v1/events/:id/production-plan/pdf","type":0,"val":"v1","end":""},{"old":"/v1/events/:id/production-plan/pdf","type":0,"val":"events","end":""},{"old":"/v1/events/:id/production-plan/pdf","type":1,"val":"id","end":""},{"old":"/v1/events/:id/production-plan/pdf","type":0,"val":"production-plan","end":""},{"old":"/v1/events/:id/production-plan/pdf","type":0,"val":"pdf","end":""}],
    types: placeholder as Registry['production_runs.production_plan_pdf']['types'],
  },
  'production_runs.return_state': {
    methods: ["GET","HEAD"],
    pattern: '/v1/events/:id/production-returns',
    tokens: [{"old":"/v1/events/:id/production-returns","type":0,"val":"v1","end":""},{"old":"/v1/events/:id/production-returns","type":0,"val":"events","end":""},{"old":"/v1/events/:id/production-returns","type":1,"val":"id","end":""},{"old":"/v1/events/:id/production-returns","type":0,"val":"production-returns","end":""}],
    types: placeholder as Registry['production_runs.return_state']['types'],
  },
  'production_runs.returns': {
    methods: ["POST"],
    pattern: '/v1/events/:id/production-returns',
    tokens: [{"old":"/v1/events/:id/production-returns","type":0,"val":"v1","end":""},{"old":"/v1/events/:id/production-returns","type":0,"val":"events","end":""},{"old":"/v1/events/:id/production-returns","type":1,"val":"id","end":""},{"old":"/v1/events/:id/production-returns","type":0,"val":"production-returns","end":""}],
    types: placeholder as Registry['production_runs.returns']['types'],
  },
  'production_runs.production_returns_pdf': {
    methods: ["GET","HEAD"],
    pattern: '/v1/events/:id/production-returns/pdf',
    tokens: [{"old":"/v1/events/:id/production-returns/pdf","type":0,"val":"v1","end":""},{"old":"/v1/events/:id/production-returns/pdf","type":0,"val":"events","end":""},{"old":"/v1/events/:id/production-returns/pdf","type":1,"val":"id","end":""},{"old":"/v1/events/:id/production-returns/pdf","type":0,"val":"production-returns","end":""},{"old":"/v1/events/:id/production-returns/pdf","type":0,"val":"pdf","end":""}],
    types: placeholder as Registry['production_runs.production_returns_pdf']['types'],
  },
  'events.run_matching': {
    methods: ["POST"],
    pattern: '/v1/events/:id/matching',
    tokens: [{"old":"/v1/events/:id/matching","type":0,"val":"v1","end":""},{"old":"/v1/events/:id/matching","type":0,"val":"events","end":""},{"old":"/v1/events/:id/matching","type":1,"val":"id","end":""},{"old":"/v1/events/:id/matching","type":0,"val":"matching","end":""}],
    types: placeholder as Registry['events.run_matching']['types'],
  },
  'events.settle': {
    methods: ["POST"],
    pattern: '/v1/events/:id/settle',
    tokens: [{"old":"/v1/events/:id/settle","type":0,"val":"v1","end":""},{"old":"/v1/events/:id/settle","type":0,"val":"events","end":""},{"old":"/v1/events/:id/settle","type":1,"val":"id","end":""},{"old":"/v1/events/:id/settle","type":0,"val":"settle","end":""}],
    types: placeholder as Registry['events.settle']['types'],
  },
  'assignments.pdf': {
    methods: ["GET","HEAD"],
    pattern: '/v1/events/:id/assignments/pdf',
    tokens: [{"old":"/v1/events/:id/assignments/pdf","type":0,"val":"v1","end":""},{"old":"/v1/events/:id/assignments/pdf","type":0,"val":"events","end":""},{"old":"/v1/events/:id/assignments/pdf","type":1,"val":"id","end":""},{"old":"/v1/events/:id/assignments/pdf","type":0,"val":"assignments","end":""},{"old":"/v1/events/:id/assignments/pdf","type":0,"val":"pdf","end":""}],
    types: placeholder as Registry['assignments.pdf']['types'],
  },
  'jobs.index': {
    methods: ["GET","HEAD"],
    pattern: '/v1/jobs',
    tokens: [{"old":"/v1/jobs","type":0,"val":"v1","end":""},{"old":"/v1/jobs","type":0,"val":"jobs","end":""}],
    types: placeholder as Registry['jobs.index']['types'],
  },
  'jobs.store': {
    methods: ["POST"],
    pattern: '/v1/jobs',
    tokens: [{"old":"/v1/jobs","type":0,"val":"v1","end":""},{"old":"/v1/jobs","type":0,"val":"jobs","end":""}],
    types: placeholder as Registry['jobs.store']['types'],
  },
  'jobs.show': {
    methods: ["GET","HEAD"],
    pattern: '/v1/jobs/:id',
    tokens: [{"old":"/v1/jobs/:id","type":0,"val":"v1","end":""},{"old":"/v1/jobs/:id","type":0,"val":"jobs","end":""},{"old":"/v1/jobs/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['jobs.show']['types'],
  },
  'jobs.update': {
    methods: ["PUT","PATCH"],
    pattern: '/v1/jobs/:id',
    tokens: [{"old":"/v1/jobs/:id","type":0,"val":"v1","end":""},{"old":"/v1/jobs/:id","type":0,"val":"jobs","end":""},{"old":"/v1/jobs/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['jobs.update']['types'],
  },
  'jobs.destroy': {
    methods: ["DELETE"],
    pattern: '/v1/jobs/:id',
    tokens: [{"old":"/v1/jobs/:id","type":0,"val":"v1","end":""},{"old":"/v1/jobs/:id","type":0,"val":"jobs","end":""},{"old":"/v1/jobs/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['jobs.destroy']['types'],
  },
  'event_jobs.index': {
    methods: ["GET","HEAD"],
    pattern: '/v1/event-jobs',
    tokens: [{"old":"/v1/event-jobs","type":0,"val":"v1","end":""},{"old":"/v1/event-jobs","type":0,"val":"event-jobs","end":""}],
    types: placeholder as Registry['event_jobs.index']['types'],
  },
  'event_jobs.store': {
    methods: ["POST"],
    pattern: '/v1/event-jobs',
    tokens: [{"old":"/v1/event-jobs","type":0,"val":"v1","end":""},{"old":"/v1/event-jobs","type":0,"val":"event-jobs","end":""}],
    types: placeholder as Registry['event_jobs.store']['types'],
  },
  'event_jobs.update': {
    methods: ["PUT","PATCH"],
    pattern: '/v1/event-jobs',
    tokens: [{"old":"/v1/event-jobs","type":0,"val":"v1","end":""},{"old":"/v1/event-jobs","type":0,"val":"event-jobs","end":""}],
    types: placeholder as Registry['event_jobs.update']['types'],
  },
  'event_jobs.destroy': {
    methods: ["DELETE"],
    pattern: '/v1/event-jobs',
    tokens: [{"old":"/v1/event-jobs","type":0,"val":"v1","end":""},{"old":"/v1/event-jobs","type":0,"val":"event-jobs","end":""}],
    types: placeholder as Registry['event_jobs.destroy']['types'],
  },
  'assignments.index': {
    methods: ["GET","HEAD"],
    pattern: '/v1/assignments',
    tokens: [{"old":"/v1/assignments","type":0,"val":"v1","end":""},{"old":"/v1/assignments","type":0,"val":"assignments","end":""}],
    types: placeholder as Registry['assignments.index']['types'],
  },
  'assignments.store': {
    methods: ["POST"],
    pattern: '/v1/assignments',
    tokens: [{"old":"/v1/assignments","type":0,"val":"v1","end":""},{"old":"/v1/assignments","type":0,"val":"assignments","end":""}],
    types: placeholder as Registry['assignments.store']['types'],
  },
  'assignments.update': {
    methods: ["PUT","PATCH"],
    pattern: '/v1/assignments',
    tokens: [{"old":"/v1/assignments","type":0,"val":"v1","end":""},{"old":"/v1/assignments","type":0,"val":"assignments","end":""}],
    types: placeholder as Registry['assignments.update']['types'],
  },
  'assignments.destroy': {
    methods: ["DELETE"],
    pattern: '/v1/assignments',
    tokens: [{"old":"/v1/assignments","type":0,"val":"v1","end":""},{"old":"/v1/assignments","type":0,"val":"assignments","end":""}],
    types: placeholder as Registry['assignments.destroy']['types'],
  },
  'responses.index': {
    methods: ["GET","HEAD"],
    pattern: '/v1/responses',
    tokens: [{"old":"/v1/responses","type":0,"val":"v1","end":""},{"old":"/v1/responses","type":0,"val":"responses","end":""}],
    types: placeholder as Registry['responses.index']['types'],
  },
  'preferences.index': {
    methods: ["GET","HEAD"],
    pattern: '/v1/preferences',
    tokens: [{"old":"/v1/preferences","type":0,"val":"v1","end":""},{"old":"/v1/preferences","type":0,"val":"preferences","end":""}],
    types: placeholder as Registry['preferences.index']['types'],
  },
  'job_eligible_members.index': {
    methods: ["GET","HEAD"],
    pattern: '/v1/job-eligible-members',
    tokens: [{"old":"/v1/job-eligible-members","type":0,"val":"v1","end":""},{"old":"/v1/job-eligible-members","type":0,"val":"job-eligible-members","end":""}],
    types: placeholder as Registry['job_eligible_members.index']['types'],
  },
  'job_eligible_members.store': {
    methods: ["POST"],
    pattern: '/v1/job-eligible-members',
    tokens: [{"old":"/v1/job-eligible-members","type":0,"val":"v1","end":""},{"old":"/v1/job-eligible-members","type":0,"val":"job-eligible-members","end":""}],
    types: placeholder as Registry['job_eligible_members.store']['types'],
  },
  'job_eligible_members.destroy': {
    methods: ["DELETE"],
    pattern: '/v1/job-eligible-members',
    tokens: [{"old":"/v1/job-eligible-members","type":0,"val":"v1","end":""},{"old":"/v1/job-eligible-members","type":0,"val":"job-eligible-members","end":""}],
    types: placeholder as Registry['job_eligible_members.destroy']['types'],
  },
  'account_preferences.preferences.mine': {
    methods: ["GET","HEAD"],
    pattern: '/v1/account/preferences',
    tokens: [{"old":"/v1/account/preferences","type":0,"val":"v1","end":""},{"old":"/v1/account/preferences","type":0,"val":"account","end":""},{"old":"/v1/account/preferences","type":0,"val":"preferences","end":""}],
    types: placeholder as Registry['account_preferences.preferences.mine']['types'],
  },
  'account_preferences.preferences.update_mine': {
    methods: ["PUT","PATCH"],
    pattern: '/v1/account/preferences',
    tokens: [{"old":"/v1/account/preferences","type":0,"val":"v1","end":""},{"old":"/v1/account/preferences","type":0,"val":"account","end":""},{"old":"/v1/account/preferences","type":0,"val":"preferences","end":""}],
    types: placeholder as Registry['account_preferences.preferences.update_mine']['types'],
  },
  'fast_passes.index': {
    methods: ["GET","HEAD"],
    pattern: '/v1/fast-passes',
    tokens: [{"old":"/v1/fast-passes","type":0,"val":"v1","end":""},{"old":"/v1/fast-passes","type":0,"val":"fast-passes","end":""}],
    types: placeholder as Registry['fast_passes.index']['types'],
  },
  'fast_passes.store': {
    methods: ["POST"],
    pattern: '/v1/fast-passes',
    tokens: [{"old":"/v1/fast-passes","type":0,"val":"v1","end":""},{"old":"/v1/fast-passes","type":0,"val":"fast-passes","end":""}],
    types: placeholder as Registry['fast_passes.store']['types'],
  },
  'fast_passes.show': {
    methods: ["GET","HEAD"],
    pattern: '/v1/fast-passes/:id',
    tokens: [{"old":"/v1/fast-passes/:id","type":0,"val":"v1","end":""},{"old":"/v1/fast-passes/:id","type":0,"val":"fast-passes","end":""},{"old":"/v1/fast-passes/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['fast_passes.show']['types'],
  },
  'fast_passes.update': {
    methods: ["PUT"],
    pattern: '/v1/fast-passes/:id',
    tokens: [{"old":"/v1/fast-passes/:id","type":0,"val":"v1","end":""},{"old":"/v1/fast-passes/:id","type":0,"val":"fast-passes","end":""},{"old":"/v1/fast-passes/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['fast_passes.update']['types'],
  },
  'fast_passes.destroy': {
    methods: ["DELETE"],
    pattern: '/v1/fast-passes/:id',
    tokens: [{"old":"/v1/fast-passes/:id","type":0,"val":"v1","end":""},{"old":"/v1/fast-passes/:id","type":0,"val":"fast-passes","end":""},{"old":"/v1/fast-passes/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['fast_passes.destroy']['types'],
  },
  'transactions.index': {
    methods: ["GET","HEAD"],
    pattern: '/v1/transactions',
    tokens: [{"old":"/v1/transactions","type":0,"val":"v1","end":""},{"old":"/v1/transactions","type":0,"val":"transactions","end":""}],
    types: placeholder as Registry['transactions.index']['types'],
  },
  'qrs.verify': {
    methods: ["POST"],
    pattern: '/v1/qr/verify',
    tokens: [{"old":"/v1/qr/verify","type":0,"val":"v1","end":""},{"old":"/v1/qr/verify","type":0,"val":"qr","end":""},{"old":"/v1/qr/verify","type":0,"val":"verify","end":""}],
    types: placeholder as Registry['qrs.verify']['types'],
  },
  'qrs.search': {
    methods: ["GET","HEAD"],
    pattern: '/v1/buyers',
    tokens: [{"old":"/v1/buyers","type":0,"val":"v1","end":""},{"old":"/v1/buyers","type":0,"val":"buyers","end":""}],
    types: placeholder as Registry['qrs.search']['types'],
  },
  'orders.set_status': {
    methods: ["PATCH"],
    pattern: '/v1/orders/:id/status',
    tokens: [{"old":"/v1/orders/:id/status","type":0,"val":"v1","end":""},{"old":"/v1/orders/:id/status","type":0,"val":"orders","end":""},{"old":"/v1/orders/:id/status","type":1,"val":"id","end":""},{"old":"/v1/orders/:id/status","type":0,"val":"status","end":""}],
    types: placeholder as Registry['orders.set_status']['types'],
  },
  'orders.destroy': {
    methods: ["DELETE"],
    pattern: '/v1/orders/:id',
    tokens: [{"old":"/v1/orders/:id","type":0,"val":"v1","end":""},{"old":"/v1/orders/:id","type":0,"val":"orders","end":""},{"old":"/v1/orders/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['orders.destroy']['types'],
  },
  'pre_orders.set_status': {
    methods: ["PATCH"],
    pattern: '/v1/pre-orders/:id/status',
    tokens: [{"old":"/v1/pre-orders/:id/status","type":0,"val":"v1","end":""},{"old":"/v1/pre-orders/:id/status","type":0,"val":"pre-orders","end":""},{"old":"/v1/pre-orders/:id/status","type":1,"val":"id","end":""},{"old":"/v1/pre-orders/:id/status","type":0,"val":"status","end":""}],
    types: placeholder as Registry['pre_orders.set_status']['types'],
  },
  'pre_orders.collect': {
    methods: ["POST"],
    pattern: '/v1/pre-orders/:id/collect',
    tokens: [{"old":"/v1/pre-orders/:id/collect","type":0,"val":"v1","end":""},{"old":"/v1/pre-orders/:id/collect","type":0,"val":"pre-orders","end":""},{"old":"/v1/pre-orders/:id/collect","type":1,"val":"id","end":""},{"old":"/v1/pre-orders/:id/collect","type":0,"val":"collect","end":""}],
    types: placeholder as Registry['pre_orders.collect']['types'],
  },
  'clients.summary': {
    methods: ["GET","HEAD"],
    pattern: '/v1/clients/summary',
    tokens: [{"old":"/v1/clients/summary","type":0,"val":"v1","end":""},{"old":"/v1/clients/summary","type":0,"val":"clients","end":""},{"old":"/v1/clients/summary","type":0,"val":"summary","end":""}],
    types: placeholder as Registry['clients.summary']['types'],
  },
  'clients.index': {
    methods: ["GET","HEAD"],
    pattern: '/v1/clients',
    tokens: [{"old":"/v1/clients","type":0,"val":"v1","end":""},{"old":"/v1/clients","type":0,"val":"clients","end":""}],
    types: placeholder as Registry['clients.index']['types'],
  },
  'clients.show': {
    methods: ["GET","HEAD"],
    pattern: '/v1/clients/:id',
    tokens: [{"old":"/v1/clients/:id","type":0,"val":"v1","end":""},{"old":"/v1/clients/:id","type":0,"val":"clients","end":""},{"old":"/v1/clients/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['clients.show']['types'],
  },
  'clients.update': {
    methods: ["PUT","PATCH"],
    pattern: '/v1/clients/:id',
    tokens: [{"old":"/v1/clients/:id","type":0,"val":"v1","end":""},{"old":"/v1/clients/:id","type":0,"val":"clients","end":""},{"old":"/v1/clients/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['clients.update']['types'],
  },
  'clients.destroy': {
    methods: ["DELETE"],
    pattern: '/v1/clients/:id',
    tokens: [{"old":"/v1/clients/:id","type":0,"val":"v1","end":""},{"old":"/v1/clients/:id","type":0,"val":"clients","end":""},{"old":"/v1/clients/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['clients.destroy']['types'],
  },
  'subscriptions.store': {
    methods: ["POST"],
    pattern: '/v1/subscriptions',
    tokens: [{"old":"/v1/subscriptions","type":0,"val":"v1","end":""},{"old":"/v1/subscriptions","type":0,"val":"subscriptions","end":""}],
    types: placeholder as Registry['subscriptions.store']['types'],
  },
  'subscriptions.destroy': {
    methods: ["DELETE"],
    pattern: '/v1/subscriptions/:userId/:fastPassId',
    tokens: [{"old":"/v1/subscriptions/:userId/:fastPassId","type":0,"val":"v1","end":""},{"old":"/v1/subscriptions/:userId/:fastPassId","type":0,"val":"subscriptions","end":""},{"old":"/v1/subscriptions/:userId/:fastPassId","type":1,"val":"userId","end":""},{"old":"/v1/subscriptions/:userId/:fastPassId","type":1,"val":"fastPassId","end":""}],
    types: placeholder as Registry['subscriptions.destroy']['types'],
  },
  'vouchers.index': {
    methods: ["GET","HEAD"],
    pattern: '/v1/vouchers',
    tokens: [{"old":"/v1/vouchers","type":0,"val":"v1","end":""},{"old":"/v1/vouchers","type":0,"val":"vouchers","end":""}],
    types: placeholder as Registry['vouchers.index']['types'],
  },
  'vouchers.store': {
    methods: ["POST"],
    pattern: '/v1/vouchers',
    tokens: [{"old":"/v1/vouchers","type":0,"val":"v1","end":""},{"old":"/v1/vouchers","type":0,"val":"vouchers","end":""}],
    types: placeholder as Registry['vouchers.store']['types'],
  },
  'vouchers.update': {
    methods: ["PUT","PATCH"],
    pattern: '/v1/vouchers/:id',
    tokens: [{"old":"/v1/vouchers/:id","type":0,"val":"v1","end":""},{"old":"/v1/vouchers/:id","type":0,"val":"vouchers","end":""},{"old":"/v1/vouchers/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['vouchers.update']['types'],
  },
  'vouchers.destroy': {
    methods: ["DELETE"],
    pattern: '/v1/vouchers/:id',
    tokens: [{"old":"/v1/vouchers/:id","type":0,"val":"v1","end":""},{"old":"/v1/vouchers/:id","type":0,"val":"vouchers","end":""},{"old":"/v1/vouchers/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['vouchers.destroy']['types'],
  },
  'logs.index': {
    methods: ["GET","HEAD"],
    pattern: '/v1/logs',
    tokens: [{"old":"/v1/logs","type":0,"val":"v1","end":""},{"old":"/v1/logs","type":0,"val":"logs","end":""}],
    types: placeholder as Registry['logs.index']['types'],
  },
  'logs.store': {
    methods: ["POST"],
    pattern: '/v1/logs',
    tokens: [{"old":"/v1/logs","type":0,"val":"v1","end":""},{"old":"/v1/logs","type":0,"val":"logs","end":""}],
    types: placeholder as Registry['logs.store']['types'],
  },
  'logs.show': {
    methods: ["GET","HEAD"],
    pattern: '/v1/logs/:id',
    tokens: [{"old":"/v1/logs/:id","type":0,"val":"v1","end":""},{"old":"/v1/logs/:id","type":0,"val":"logs","end":""},{"old":"/v1/logs/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['logs.show']['types'],
  },
  'logs.update': {
    methods: ["PUT","PATCH"],
    pattern: '/v1/logs/:id',
    tokens: [{"old":"/v1/logs/:id","type":0,"val":"v1","end":""},{"old":"/v1/logs/:id","type":0,"val":"logs","end":""},{"old":"/v1/logs/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['logs.update']['types'],
  },
  'logs.destroy': {
    methods: ["DELETE"],
    pattern: '/v1/logs/:id',
    tokens: [{"old":"/v1/logs/:id","type":0,"val":"v1","end":""},{"old":"/v1/logs/:id","type":0,"val":"logs","end":""},{"old":"/v1/logs/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['logs.destroy']['types'],
  },
  'sessions.sessions.index': {
    methods: ["GET","HEAD"],
    pattern: '/v1/account/sessions',
    tokens: [{"old":"/v1/account/sessions","type":0,"val":"v1","end":""},{"old":"/v1/account/sessions","type":0,"val":"account","end":""},{"old":"/v1/account/sessions","type":0,"val":"sessions","end":""}],
    types: placeholder as Registry['sessions.sessions.index']['types'],
  },
  'sessions.sessions.destroy': {
    methods: ["DELETE"],
    pattern: '/v1/account/sessions/:id',
    tokens: [{"old":"/v1/account/sessions/:id","type":0,"val":"v1","end":""},{"old":"/v1/account/sessions/:id","type":0,"val":"account","end":""},{"old":"/v1/account/sessions/:id","type":0,"val":"sessions","end":""},{"old":"/v1/account/sessions/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['sessions.sessions.destroy']['types'],
  },
  'notifications.notifications.index': {
    methods: ["GET","HEAD"],
    pattern: '/v1/account/notifications',
    tokens: [{"old":"/v1/account/notifications","type":0,"val":"v1","end":""},{"old":"/v1/account/notifications","type":0,"val":"account","end":""},{"old":"/v1/account/notifications","type":0,"val":"notifications","end":""}],
    types: placeholder as Registry['notifications.notifications.index']['types'],
  },
  'notifications.notifications.mark_read': {
    methods: ["PATCH"],
    pattern: '/v1/account/notifications/:id/read',
    tokens: [{"old":"/v1/account/notifications/:id/read","type":0,"val":"v1","end":""},{"old":"/v1/account/notifications/:id/read","type":0,"val":"account","end":""},{"old":"/v1/account/notifications/:id/read","type":0,"val":"notifications","end":""},{"old":"/v1/account/notifications/:id/read","type":1,"val":"id","end":""},{"old":"/v1/account/notifications/:id/read","type":0,"val":"read","end":""}],
    types: placeholder as Registry['notifications.notifications.mark_read']['types'],
  },
  'notifications.notifications.mark_all_read': {
    methods: ["POST"],
    pattern: '/v1/account/notifications/read-all',
    tokens: [{"old":"/v1/account/notifications/read-all","type":0,"val":"v1","end":""},{"old":"/v1/account/notifications/read-all","type":0,"val":"account","end":""},{"old":"/v1/account/notifications/read-all","type":0,"val":"notifications","end":""},{"old":"/v1/account/notifications/read-all","type":0,"val":"read-all","end":""}],
    types: placeholder as Registry['notifications.notifications.mark_all_read']['types'],
  },
  'tickets.tickets.index': {
    methods: ["GET","HEAD"],
    pattern: '/v1/tickets',
    tokens: [{"old":"/v1/tickets","type":0,"val":"v1","end":""},{"old":"/v1/tickets","type":0,"val":"tickets","end":""}],
    types: placeholder as Registry['tickets.tickets.index']['types'],
  },
  'tickets.tickets.store': {
    methods: ["POST"],
    pattern: '/v1/tickets',
    tokens: [{"old":"/v1/tickets","type":0,"val":"v1","end":""},{"old":"/v1/tickets","type":0,"val":"tickets","end":""}],
    types: placeholder as Registry['tickets.tickets.store']['types'],
  },
  'tickets.tickets.show': {
    methods: ["GET","HEAD"],
    pattern: '/v1/tickets/:id',
    tokens: [{"old":"/v1/tickets/:id","type":0,"val":"v1","end":""},{"old":"/v1/tickets/:id","type":0,"val":"tickets","end":""},{"old":"/v1/tickets/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['tickets.tickets.show']['types'],
  },
  'tickets.tickets.reply': {
    methods: ["POST"],
    pattern: '/v1/tickets/:id/messages',
    tokens: [{"old":"/v1/tickets/:id/messages","type":0,"val":"v1","end":""},{"old":"/v1/tickets/:id/messages","type":0,"val":"tickets","end":""},{"old":"/v1/tickets/:id/messages","type":1,"val":"id","end":""},{"old":"/v1/tickets/:id/messages","type":0,"val":"messages","end":""}],
    types: placeholder as Registry['tickets.tickets.reply']['types'],
  },
  'tickets.tickets.set_status': {
    methods: ["PATCH"],
    pattern: '/v1/tickets/:id/status',
    tokens: [{"old":"/v1/tickets/:id/status","type":0,"val":"v1","end":""},{"old":"/v1/tickets/:id/status","type":0,"val":"tickets","end":""},{"old":"/v1/tickets/:id/status","type":1,"val":"id","end":""},{"old":"/v1/tickets/:id/status","type":0,"val":"status","end":""}],
    types: placeholder as Registry['tickets.tickets.set_status']['types'],
  },
  'event_stream': {
    methods: ["GET","HEAD"],
    pattern: '/__transmit/events',
    tokens: [{"old":"/__transmit/events","type":0,"val":"__transmit","end":""},{"old":"/__transmit/events","type":0,"val":"events","end":""}],
    types: placeholder as Registry['event_stream']['types'],
  },
  'subscribe': {
    methods: ["POST"],
    pattern: '/__transmit/subscribe',
    tokens: [{"old":"/__transmit/subscribe","type":0,"val":"__transmit","end":""},{"old":"/__transmit/subscribe","type":0,"val":"subscribe","end":""}],
    types: placeholder as Registry['subscribe']['types'],
  },
  'unsubscribe': {
    methods: ["POST"],
    pattern: '/__transmit/unsubscribe',
    tokens: [{"old":"/__transmit/unsubscribe","type":0,"val":"__transmit","end":""},{"old":"/__transmit/unsubscribe","type":0,"val":"unsubscribe","end":""}],
    types: placeholder as Registry['unsubscribe']['types'],
  },
} as const satisfies Record<string, AdonisEndpoint>

export { routes }

export const registry = {
  routes,
  $tree: {} as ApiDefinition,
}

declare module '@tuyau/core/types' {
  export interface UserRegistry {
    routes: typeof routes
    $tree: ApiDefinition
  }
}
