/* eslint-disable prettier/prettier */
import type { AdonisEndpoint } from '@tuyau/core/types'
import type { Registry } from './schema.d.ts'
import type { ApiDefinition } from './tree.d.ts'

const placeholder: any = {}

const routes = {
  'auth.new_account.store': {
    methods: ["POST"],
    pattern: '/v1/auth/signup',
    tokens: [{"old":"/v1/auth/signup","type":0,"val":"v1","end":""},{"old":"/v1/auth/signup","type":0,"val":"auth","end":""},{"old":"/v1/auth/signup","type":0,"val":"signup","end":""}],
    types: placeholder as Registry['auth.new_account.store']['types'],
  },
  'auth.access_token.store': {
    methods: ["POST"],
    pattern: '/v1/auth/login',
    tokens: [{"old":"/v1/auth/login","type":0,"val":"v1","end":""},{"old":"/v1/auth/login","type":0,"val":"auth","end":""},{"old":"/v1/auth/login","type":0,"val":"login","end":""}],
    types: placeholder as Registry['auth.access_token.store']['types'],
  },
  'auth.access_token.destroy': {
    methods: ["POST"],
    pattern: '/v1/auth/logout',
    tokens: [{"old":"/v1/auth/logout","type":0,"val":"v1","end":""},{"old":"/v1/auth/logout","type":0,"val":"auth","end":""},{"old":"/v1/auth/logout","type":0,"val":"logout","end":""}],
    types: placeholder as Registry['auth.access_token.destroy']['types'],
  },
  'auth.access_token.destroy_all': {
    methods: ["DELETE"],
    pattern: '/v1/auth/logout-all',
    tokens: [{"old":"/v1/auth/logout-all","type":0,"val":"v1","end":""},{"old":"/v1/auth/logout-all","type":0,"val":"auth","end":""},{"old":"/v1/auth/logout-all","type":0,"val":"logout-all","end":""}],
    types: placeholder as Registry['auth.access_token.destroy_all']['types'],
  },
  'profile.profile.show': {
    methods: ["GET","HEAD"],
    pattern: '/v1/account/profile',
    tokens: [{"old":"/v1/account/profile","type":0,"val":"v1","end":""},{"old":"/v1/account/profile","type":0,"val":"account","end":""},{"old":"/v1/account/profile","type":0,"val":"profile","end":""}],
    types: placeholder as Registry['profile.profile.show']['types'],
  },
  'members.index': {
    methods: ["GET","HEAD"],
    pattern: '/v1/members',
    tokens: [{"old":"/v1/members","type":0,"val":"v1","end":""},{"old":"/v1/members","type":0,"val":"members","end":""}],
    types: placeholder as Registry['members.index']['types'],
  },
  'members.store': {
    methods: ["POST"],
    pattern: '/v1/members',
    tokens: [{"old":"/v1/members","type":0,"val":"v1","end":""},{"old":"/v1/members","type":0,"val":"members","end":""}],
    types: placeholder as Registry['members.store']['types'],
  },
  'members.show': {
    methods: ["GET","HEAD"],
    pattern: '/v1/members/:id',
    tokens: [{"old":"/v1/members/:id","type":0,"val":"v1","end":""},{"old":"/v1/members/:id","type":0,"val":"members","end":""},{"old":"/v1/members/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['members.show']['types'],
  },
  'members.update': {
    methods: ["PUT","PATCH"],
    pattern: '/v1/members/:id',
    tokens: [{"old":"/v1/members/:id","type":0,"val":"v1","end":""},{"old":"/v1/members/:id","type":0,"val":"members","end":""},{"old":"/v1/members/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['members.update']['types'],
  },
  'members.destroy': {
    methods: ["DELETE"],
    pattern: '/v1/members/:id',
    tokens: [{"old":"/v1/members/:id","type":0,"val":"v1","end":""},{"old":"/v1/members/:id","type":0,"val":"members","end":""},{"old":"/v1/members/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['members.destroy']['types'],
  },
  'roles.index': {
    methods: ["GET","HEAD"],
    pattern: '/v1/roles',
    tokens: [{"old":"/v1/roles","type":0,"val":"v1","end":""},{"old":"/v1/roles","type":0,"val":"roles","end":""}],
    types: placeholder as Registry['roles.index']['types'],
  },
  'roles.store': {
    methods: ["POST"],
    pattern: '/v1/roles',
    tokens: [{"old":"/v1/roles","type":0,"val":"v1","end":""},{"old":"/v1/roles","type":0,"val":"roles","end":""}],
    types: placeholder as Registry['roles.store']['types'],
  },
  'roles.show': {
    methods: ["GET","HEAD"],
    pattern: '/v1/roles/:id',
    tokens: [{"old":"/v1/roles/:id","type":0,"val":"v1","end":""},{"old":"/v1/roles/:id","type":0,"val":"roles","end":""},{"old":"/v1/roles/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['roles.show']['types'],
  },
  'roles.update': {
    methods: ["PUT","PATCH"],
    pattern: '/v1/roles/:id',
    tokens: [{"old":"/v1/roles/:id","type":0,"val":"v1","end":""},{"old":"/v1/roles/:id","type":0,"val":"roles","end":""},{"old":"/v1/roles/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['roles.update']['types'],
  },
  'roles.destroy': {
    methods: ["DELETE"],
    pattern: '/v1/roles/:id',
    tokens: [{"old":"/v1/roles/:id","type":0,"val":"v1","end":""},{"old":"/v1/roles/:id","type":0,"val":"roles","end":""},{"old":"/v1/roles/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['roles.destroy']['types'],
  },
  'permissions.index': {
    methods: ["GET","HEAD"],
    pattern: '/v1/permissions',
    tokens: [{"old":"/v1/permissions","type":0,"val":"v1","end":""},{"old":"/v1/permissions","type":0,"val":"permissions","end":""}],
    types: placeholder as Registry['permissions.index']['types'],
  },
  'permissions.store': {
    methods: ["POST"],
    pattern: '/v1/permissions',
    tokens: [{"old":"/v1/permissions","type":0,"val":"v1","end":""},{"old":"/v1/permissions","type":0,"val":"permissions","end":""}],
    types: placeholder as Registry['permissions.store']['types'],
  },
  'permissions.show': {
    methods: ["GET","HEAD"],
    pattern: '/v1/permissions/:id',
    tokens: [{"old":"/v1/permissions/:id","type":0,"val":"v1","end":""},{"old":"/v1/permissions/:id","type":0,"val":"permissions","end":""},{"old":"/v1/permissions/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['permissions.show']['types'],
  },
  'permissions.update': {
    methods: ["PUT","PATCH"],
    pattern: '/v1/permissions/:id',
    tokens: [{"old":"/v1/permissions/:id","type":0,"val":"v1","end":""},{"old":"/v1/permissions/:id","type":0,"val":"permissions","end":""},{"old":"/v1/permissions/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['permissions.update']['types'],
  },
  'permissions.destroy': {
    methods: ["DELETE"],
    pattern: '/v1/permissions/:id',
    tokens: [{"old":"/v1/permissions/:id","type":0,"val":"v1","end":""},{"old":"/v1/permissions/:id","type":0,"val":"permissions","end":""},{"old":"/v1/permissions/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['permissions.destroy']['types'],
  },
  'categories.index': {
    methods: ["GET","HEAD"],
    pattern: '/v1/categories',
    tokens: [{"old":"/v1/categories","type":0,"val":"v1","end":""},{"old":"/v1/categories","type":0,"val":"categories","end":""}],
    types: placeholder as Registry['categories.index']['types'],
  },
  'categories.store': {
    methods: ["POST"],
    pattern: '/v1/categories',
    tokens: [{"old":"/v1/categories","type":0,"val":"v1","end":""},{"old":"/v1/categories","type":0,"val":"categories","end":""}],
    types: placeholder as Registry['categories.store']['types'],
  },
  'categories.show': {
    methods: ["GET","HEAD"],
    pattern: '/v1/categories/:id',
    tokens: [{"old":"/v1/categories/:id","type":0,"val":"v1","end":""},{"old":"/v1/categories/:id","type":0,"val":"categories","end":""},{"old":"/v1/categories/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['categories.show']['types'],
  },
  'categories.update': {
    methods: ["PUT","PATCH"],
    pattern: '/v1/categories/:id',
    tokens: [{"old":"/v1/categories/:id","type":0,"val":"v1","end":""},{"old":"/v1/categories/:id","type":0,"val":"categories","end":""},{"old":"/v1/categories/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['categories.update']['types'],
  },
  'categories.destroy': {
    methods: ["DELETE"],
    pattern: '/v1/categories/:id',
    tokens: [{"old":"/v1/categories/:id","type":0,"val":"v1","end":""},{"old":"/v1/categories/:id","type":0,"val":"categories","end":""},{"old":"/v1/categories/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['categories.destroy']['types'],
  },
  'products.summary': {
    methods: ["GET","HEAD"],
    pattern: '/v1/products/summary',
    tokens: [{"old":"/v1/products/summary","type":0,"val":"v1","end":""},{"old":"/v1/products/summary","type":0,"val":"products","end":""},{"old":"/v1/products/summary","type":0,"val":"summary","end":""}],
    types: placeholder as Registry['products.summary']['types'],
  },
  'products.ingredients': {
    methods: ["GET","HEAD"],
    pattern: '/v1/products/:id/ingredients',
    tokens: [{"old":"/v1/products/:id/ingredients","type":0,"val":"v1","end":""},{"old":"/v1/products/:id/ingredients","type":0,"val":"products","end":""},{"old":"/v1/products/:id/ingredients","type":1,"val":"id","end":""},{"old":"/v1/products/:id/ingredients","type":0,"val":"ingredients","end":""}],
    types: placeholder as Registry['products.ingredients']['types'],
  },
  'products.index': {
    methods: ["GET","HEAD"],
    pattern: '/v1/products',
    tokens: [{"old":"/v1/products","type":0,"val":"v1","end":""},{"old":"/v1/products","type":0,"val":"products","end":""}],
    types: placeholder as Registry['products.index']['types'],
  },
  'products.store': {
    methods: ["POST"],
    pattern: '/v1/products',
    tokens: [{"old":"/v1/products","type":0,"val":"v1","end":""},{"old":"/v1/products","type":0,"val":"products","end":""}],
    types: placeholder as Registry['products.store']['types'],
  },
  'products.show': {
    methods: ["GET","HEAD"],
    pattern: '/v1/products/:id',
    tokens: [{"old":"/v1/products/:id","type":0,"val":"v1","end":""},{"old":"/v1/products/:id","type":0,"val":"products","end":""},{"old":"/v1/products/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['products.show']['types'],
  },
  'products.update': {
    methods: ["PUT","PATCH"],
    pattern: '/v1/products/:id',
    tokens: [{"old":"/v1/products/:id","type":0,"val":"v1","end":""},{"old":"/v1/products/:id","type":0,"val":"products","end":""},{"old":"/v1/products/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['products.update']['types'],
  },
  'products.destroy': {
    methods: ["DELETE"],
    pattern: '/v1/products/:id',
    tokens: [{"old":"/v1/products/:id","type":0,"val":"v1","end":""},{"old":"/v1/products/:id","type":0,"val":"products","end":""},{"old":"/v1/products/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['products.destroy']['types'],
  },
  'goods.index': {
    methods: ["GET","HEAD"],
    pattern: '/v1/goods',
    tokens: [{"old":"/v1/goods","type":0,"val":"v1","end":""},{"old":"/v1/goods","type":0,"val":"goods","end":""}],
    types: placeholder as Registry['goods.index']['types'],
  },
  'goods.store': {
    methods: ["POST"],
    pattern: '/v1/goods',
    tokens: [{"old":"/v1/goods","type":0,"val":"v1","end":""},{"old":"/v1/goods","type":0,"val":"goods","end":""}],
    types: placeholder as Registry['goods.store']['types'],
  },
  'goods.show': {
    methods: ["GET","HEAD"],
    pattern: '/v1/goods/:id',
    tokens: [{"old":"/v1/goods/:id","type":0,"val":"v1","end":""},{"old":"/v1/goods/:id","type":0,"val":"goods","end":""},{"old":"/v1/goods/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['goods.show']['types'],
  },
  'goods.update': {
    methods: ["PUT","PATCH"],
    pattern: '/v1/goods/:id',
    tokens: [{"old":"/v1/goods/:id","type":0,"val":"v1","end":""},{"old":"/v1/goods/:id","type":0,"val":"goods","end":""},{"old":"/v1/goods/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['goods.update']['types'],
  },
  'goods.destroy': {
    methods: ["DELETE"],
    pattern: '/v1/goods/:id',
    tokens: [{"old":"/v1/goods/:id","type":0,"val":"v1","end":""},{"old":"/v1/goods/:id","type":0,"val":"goods","end":""},{"old":"/v1/goods/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['goods.destroy']['types'],
  },
  'furnitures.index': {
    methods: ["GET","HEAD"],
    pattern: '/v1/furnitures',
    tokens: [{"old":"/v1/furnitures","type":0,"val":"v1","end":""},{"old":"/v1/furnitures","type":0,"val":"furnitures","end":""}],
    types: placeholder as Registry['furnitures.index']['types'],
  },
  'furnitures.store': {
    methods: ["POST"],
    pattern: '/v1/furnitures',
    tokens: [{"old":"/v1/furnitures","type":0,"val":"v1","end":""},{"old":"/v1/furnitures","type":0,"val":"furnitures","end":""}],
    types: placeholder as Registry['furnitures.store']['types'],
  },
  'furnitures.show': {
    methods: ["GET","HEAD"],
    pattern: '/v1/furnitures/:id',
    tokens: [{"old":"/v1/furnitures/:id","type":0,"val":"v1","end":""},{"old":"/v1/furnitures/:id","type":0,"val":"furnitures","end":""},{"old":"/v1/furnitures/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['furnitures.show']['types'],
  },
  'furnitures.update': {
    methods: ["PUT","PATCH"],
    pattern: '/v1/furnitures/:id',
    tokens: [{"old":"/v1/furnitures/:id","type":0,"val":"v1","end":""},{"old":"/v1/furnitures/:id","type":0,"val":"furnitures","end":""},{"old":"/v1/furnitures/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['furnitures.update']['types'],
  },
  'furnitures.destroy': {
    methods: ["DELETE"],
    pattern: '/v1/furnitures/:id',
    tokens: [{"old":"/v1/furnitures/:id","type":0,"val":"v1","end":""},{"old":"/v1/furnitures/:id","type":0,"val":"furnitures","end":""},{"old":"/v1/furnitures/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['furnitures.destroy']['types'],
  },
  'suppliers.index': {
    methods: ["GET","HEAD"],
    pattern: '/v1/suppliers',
    tokens: [{"old":"/v1/suppliers","type":0,"val":"v1","end":""},{"old":"/v1/suppliers","type":0,"val":"suppliers","end":""}],
    types: placeholder as Registry['suppliers.index']['types'],
  },
  'suppliers.store': {
    methods: ["POST"],
    pattern: '/v1/suppliers',
    tokens: [{"old":"/v1/suppliers","type":0,"val":"v1","end":""},{"old":"/v1/suppliers","type":0,"val":"suppliers","end":""}],
    types: placeholder as Registry['suppliers.store']['types'],
  },
  'suppliers.show': {
    methods: ["GET","HEAD"],
    pattern: '/v1/suppliers/:id',
    tokens: [{"old":"/v1/suppliers/:id","type":0,"val":"v1","end":""},{"old":"/v1/suppliers/:id","type":0,"val":"suppliers","end":""},{"old":"/v1/suppliers/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['suppliers.show']['types'],
  },
  'suppliers.update': {
    methods: ["PUT","PATCH"],
    pattern: '/v1/suppliers/:id',
    tokens: [{"old":"/v1/suppliers/:id","type":0,"val":"v1","end":""},{"old":"/v1/suppliers/:id","type":0,"val":"suppliers","end":""},{"old":"/v1/suppliers/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['suppliers.update']['types'],
  },
  'suppliers.destroy': {
    methods: ["DELETE"],
    pattern: '/v1/suppliers/:id',
    tokens: [{"old":"/v1/suppliers/:id","type":0,"val":"v1","end":""},{"old":"/v1/suppliers/:id","type":0,"val":"suppliers","end":""},{"old":"/v1/suppliers/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['suppliers.destroy']['types'],
  },
  'stocks.index': {
    methods: ["GET","HEAD"],
    pattern: '/v1/stocks',
    tokens: [{"old":"/v1/stocks","type":0,"val":"v1","end":""},{"old":"/v1/stocks","type":0,"val":"stocks","end":""}],
    types: placeholder as Registry['stocks.index']['types'],
  },
  'stocks.batches': {
    methods: ["GET","HEAD"],
    pattern: '/v1/stocks/:id/batches',
    tokens: [{"old":"/v1/stocks/:id/batches","type":0,"val":"v1","end":""},{"old":"/v1/stocks/:id/batches","type":0,"val":"stocks","end":""},{"old":"/v1/stocks/:id/batches","type":1,"val":"id","end":""},{"old":"/v1/stocks/:id/batches","type":0,"val":"batches","end":""}],
    types: placeholder as Registry['stocks.batches']['types'],
  },
  'stocks.discard': {
    methods: ["POST"],
    pattern: '/v1/stocks/:id/batches/:batchId/discard',
    tokens: [{"old":"/v1/stocks/:id/batches/:batchId/discard","type":0,"val":"v1","end":""},{"old":"/v1/stocks/:id/batches/:batchId/discard","type":0,"val":"stocks","end":""},{"old":"/v1/stocks/:id/batches/:batchId/discard","type":1,"val":"id","end":""},{"old":"/v1/stocks/:id/batches/:batchId/discard","type":0,"val":"batches","end":""},{"old":"/v1/stocks/:id/batches/:batchId/discard","type":1,"val":"batchId","end":""},{"old":"/v1/stocks/:id/batches/:batchId/discard","type":0,"val":"discard","end":""}],
    types: placeholder as Registry['stocks.discard']['types'],
  },
  'stock_batches.index': {
    methods: ["GET","HEAD"],
    pattern: '/v1/stock-batches',
    tokens: [{"old":"/v1/stock-batches","type":0,"val":"v1","end":""},{"old":"/v1/stock-batches","type":0,"val":"stock-batches","end":""}],
    types: placeholder as Registry['stock_batches.index']['types'],
  },
  'stock_batches.store': {
    methods: ["POST"],
    pattern: '/v1/stock-batches',
    tokens: [{"old":"/v1/stock-batches","type":0,"val":"v1","end":""},{"old":"/v1/stock-batches","type":0,"val":"stock-batches","end":""}],
    types: placeholder as Registry['stock_batches.store']['types'],
  },
  'stock_batches.show': {
    methods: ["GET","HEAD"],
    pattern: '/v1/stock-batches/:id',
    tokens: [{"old":"/v1/stock-batches/:id","type":0,"val":"v1","end":""},{"old":"/v1/stock-batches/:id","type":0,"val":"stock-batches","end":""},{"old":"/v1/stock-batches/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['stock_batches.show']['types'],
  },
  'stock_batches.update': {
    methods: ["PUT","PATCH"],
    pattern: '/v1/stock-batches/:id',
    tokens: [{"old":"/v1/stock-batches/:id","type":0,"val":"v1","end":""},{"old":"/v1/stock-batches/:id","type":0,"val":"stock-batches","end":""},{"old":"/v1/stock-batches/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['stock_batches.update']['types'],
  },
  'stock_batches.destroy': {
    methods: ["DELETE"],
    pattern: '/v1/stock-batches/:id',
    tokens: [{"old":"/v1/stock-batches/:id","type":0,"val":"v1","end":""},{"old":"/v1/stock-batches/:id","type":0,"val":"stock-batches","end":""},{"old":"/v1/stock-batches/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['stock_batches.destroy']['types'],
  },
  'stock_movements.index': {
    methods: ["GET","HEAD"],
    pattern: '/v1/stock-movements',
    tokens: [{"old":"/v1/stock-movements","type":0,"val":"v1","end":""},{"old":"/v1/stock-movements","type":0,"val":"stock-movements","end":""}],
    types: placeholder as Registry['stock_movements.index']['types'],
  },
  'stock_movements.store': {
    methods: ["POST"],
    pattern: '/v1/stock-movements',
    tokens: [{"old":"/v1/stock-movements","type":0,"val":"v1","end":""},{"old":"/v1/stock-movements","type":0,"val":"stock-movements","end":""}],
    types: placeholder as Registry['stock_movements.store']['types'],
  },
  'stock_movements.show': {
    methods: ["GET","HEAD"],
    pattern: '/v1/stock-movements/:id',
    tokens: [{"old":"/v1/stock-movements/:id","type":0,"val":"v1","end":""},{"old":"/v1/stock-movements/:id","type":0,"val":"stock-movements","end":""},{"old":"/v1/stock-movements/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['stock_movements.show']['types'],
  },
  'stock_movements.update': {
    methods: ["PUT","PATCH"],
    pattern: '/v1/stock-movements/:id',
    tokens: [{"old":"/v1/stock-movements/:id","type":0,"val":"v1","end":""},{"old":"/v1/stock-movements/:id","type":0,"val":"stock-movements","end":""},{"old":"/v1/stock-movements/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['stock_movements.update']['types'],
  },
  'stock_movements.destroy': {
    methods: ["DELETE"],
    pattern: '/v1/stock-movements/:id',
    tokens: [{"old":"/v1/stock-movements/:id","type":0,"val":"v1","end":""},{"old":"/v1/stock-movements/:id","type":0,"val":"stock-movements","end":""},{"old":"/v1/stock-movements/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['stock_movements.destroy']['types'],
  },
  'restocks.index': {
    methods: ["GET","HEAD"],
    pattern: '/v1/restocks',
    tokens: [{"old":"/v1/restocks","type":0,"val":"v1","end":""},{"old":"/v1/restocks","type":0,"val":"restocks","end":""}],
    types: placeholder as Registry['restocks.index']['types'],
  },
  'restocks.store': {
    methods: ["POST"],
    pattern: '/v1/restocks',
    tokens: [{"old":"/v1/restocks","type":0,"val":"v1","end":""},{"old":"/v1/restocks","type":0,"val":"restocks","end":""}],
    types: placeholder as Registry['restocks.store']['types'],
  },
  'restocks.show': {
    methods: ["GET","HEAD"],
    pattern: '/v1/restocks/:id',
    tokens: [{"old":"/v1/restocks/:id","type":0,"val":"v1","end":""},{"old":"/v1/restocks/:id","type":0,"val":"restocks","end":""},{"old":"/v1/restocks/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['restocks.show']['types'],
  },
  'restocks.update': {
    methods: ["PUT","PATCH"],
    pattern: '/v1/restocks/:id',
    tokens: [{"old":"/v1/restocks/:id","type":0,"val":"v1","end":""},{"old":"/v1/restocks/:id","type":0,"val":"restocks","end":""},{"old":"/v1/restocks/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['restocks.update']['types'],
  },
  'restocks.destroy': {
    methods: ["DELETE"],
    pattern: '/v1/restocks/:id',
    tokens: [{"old":"/v1/restocks/:id","type":0,"val":"v1","end":""},{"old":"/v1/restocks/:id","type":0,"val":"restocks","end":""},{"old":"/v1/restocks/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['restocks.destroy']['types'],
  },
  'events.index': {
    methods: ["GET","HEAD"],
    pattern: '/v1/events',
    tokens: [{"old":"/v1/events","type":0,"val":"v1","end":""},{"old":"/v1/events","type":0,"val":"events","end":""}],
    types: placeholder as Registry['events.index']['types'],
  },
  'events.store': {
    methods: ["POST"],
    pattern: '/v1/events',
    tokens: [{"old":"/v1/events","type":0,"val":"v1","end":""},{"old":"/v1/events","type":0,"val":"events","end":""}],
    types: placeholder as Registry['events.store']['types'],
  },
  'events.show': {
    methods: ["GET","HEAD"],
    pattern: '/v1/events/:id',
    tokens: [{"old":"/v1/events/:id","type":0,"val":"v1","end":""},{"old":"/v1/events/:id","type":0,"val":"events","end":""},{"old":"/v1/events/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['events.show']['types'],
  },
  'events.update': {
    methods: ["PUT","PATCH"],
    pattern: '/v1/events/:id',
    tokens: [{"old":"/v1/events/:id","type":0,"val":"v1","end":""},{"old":"/v1/events/:id","type":0,"val":"events","end":""},{"old":"/v1/events/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['events.update']['types'],
  },
  'events.destroy': {
    methods: ["DELETE"],
    pattern: '/v1/events/:id',
    tokens: [{"old":"/v1/events/:id","type":0,"val":"v1","end":""},{"old":"/v1/events/:id","type":0,"val":"events","end":""},{"old":"/v1/events/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['events.destroy']['types'],
  },
  'events.get_response': {
    methods: ["GET","HEAD"],
    pattern: '/v1/events/:id/response',
    tokens: [{"old":"/v1/events/:id/response","type":0,"val":"v1","end":""},{"old":"/v1/events/:id/response","type":0,"val":"events","end":""},{"old":"/v1/events/:id/response","type":1,"val":"id","end":""},{"old":"/v1/events/:id/response","type":0,"val":"response","end":""}],
    types: placeholder as Registry['events.get_response']['types'],
  },
  'events.set_response': {
    methods: ["POST"],
    pattern: '/v1/events/:id/response',
    tokens: [{"old":"/v1/events/:id/response","type":0,"val":"v1","end":""},{"old":"/v1/events/:id/response","type":0,"val":"events","end":""},{"old":"/v1/events/:id/response","type":1,"val":"id","end":""},{"old":"/v1/events/:id/response","type":0,"val":"response","end":""}],
    types: placeholder as Registry['events.set_response']['types'],
  },
  'events.roster': {
    methods: ["GET","HEAD"],
    pattern: '/v1/events/:id/roster',
    tokens: [{"old":"/v1/events/:id/roster","type":0,"val":"v1","end":""},{"old":"/v1/events/:id/roster","type":0,"val":"events","end":""},{"old":"/v1/events/:id/roster","type":1,"val":"id","end":""},{"old":"/v1/events/:id/roster","type":0,"val":"roster","end":""}],
    types: placeholder as Registry['events.roster']['types'],
  },
  'events.run_matching': {
    methods: ["POST"],
    pattern: '/v1/events/:id/matching',
    tokens: [{"old":"/v1/events/:id/matching","type":0,"val":"v1","end":""},{"old":"/v1/events/:id/matching","type":0,"val":"events","end":""},{"old":"/v1/events/:id/matching","type":1,"val":"id","end":""},{"old":"/v1/events/:id/matching","type":0,"val":"matching","end":""}],
    types: placeholder as Registry['events.run_matching']['types'],
  },
  'jobs.index': {
    methods: ["GET","HEAD"],
    pattern: '/v1/jobs',
    tokens: [{"old":"/v1/jobs","type":0,"val":"v1","end":""},{"old":"/v1/jobs","type":0,"val":"jobs","end":""}],
    types: placeholder as Registry['jobs.index']['types'],
  },
  'jobs.store': {
    methods: ["POST"],
    pattern: '/v1/jobs',
    tokens: [{"old":"/v1/jobs","type":0,"val":"v1","end":""},{"old":"/v1/jobs","type":0,"val":"jobs","end":""}],
    types: placeholder as Registry['jobs.store']['types'],
  },
  'jobs.show': {
    methods: ["GET","HEAD"],
    pattern: '/v1/jobs/:id',
    tokens: [{"old":"/v1/jobs/:id","type":0,"val":"v1","end":""},{"old":"/v1/jobs/:id","type":0,"val":"jobs","end":""},{"old":"/v1/jobs/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['jobs.show']['types'],
  },
  'jobs.update': {
    methods: ["PUT","PATCH"],
    pattern: '/v1/jobs/:id',
    tokens: [{"old":"/v1/jobs/:id","type":0,"val":"v1","end":""},{"old":"/v1/jobs/:id","type":0,"val":"jobs","end":""},{"old":"/v1/jobs/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['jobs.update']['types'],
  },
  'jobs.destroy': {
    methods: ["DELETE"],
    pattern: '/v1/jobs/:id',
    tokens: [{"old":"/v1/jobs/:id","type":0,"val":"v1","end":""},{"old":"/v1/jobs/:id","type":0,"val":"jobs","end":""},{"old":"/v1/jobs/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['jobs.destroy']['types'],
  },
  'event_jobs.index': {
    methods: ["GET","HEAD"],
    pattern: '/v1/event-jobs',
    tokens: [{"old":"/v1/event-jobs","type":0,"val":"v1","end":""},{"old":"/v1/event-jobs","type":0,"val":"event-jobs","end":""}],
    types: placeholder as Registry['event_jobs.index']['types'],
  },
  'event_jobs.store': {
    methods: ["POST"],
    pattern: '/v1/event-jobs',
    tokens: [{"old":"/v1/event-jobs","type":0,"val":"v1","end":""},{"old":"/v1/event-jobs","type":0,"val":"event-jobs","end":""}],
    types: placeholder as Registry['event_jobs.store']['types'],
  },
  'event_jobs.update': {
    methods: ["PUT","PATCH"],
    pattern: '/v1/event-jobs',
    tokens: [{"old":"/v1/event-jobs","type":0,"val":"v1","end":""},{"old":"/v1/event-jobs","type":0,"val":"event-jobs","end":""}],
    types: placeholder as Registry['event_jobs.update']['types'],
  },
  'event_jobs.destroy': {
    methods: ["DELETE"],
    pattern: '/v1/event-jobs',
    tokens: [{"old":"/v1/event-jobs","type":0,"val":"v1","end":""},{"old":"/v1/event-jobs","type":0,"val":"event-jobs","end":""}],
    types: placeholder as Registry['event_jobs.destroy']['types'],
  },
  'assignments.index': {
    methods: ["GET","HEAD"],
    pattern: '/v1/assignments',
    tokens: [{"old":"/v1/assignments","type":0,"val":"v1","end":""},{"old":"/v1/assignments","type":0,"val":"assignments","end":""}],
    types: placeholder as Registry['assignments.index']['types'],
  },
  'assignments.store': {
    methods: ["POST"],
    pattern: '/v1/assignments',
    tokens: [{"old":"/v1/assignments","type":0,"val":"v1","end":""},{"old":"/v1/assignments","type":0,"val":"assignments","end":""}],
    types: placeholder as Registry['assignments.store']['types'],
  },
  'assignments.update': {
    methods: ["PUT","PATCH"],
    pattern: '/v1/assignments',
    tokens: [{"old":"/v1/assignments","type":0,"val":"v1","end":""},{"old":"/v1/assignments","type":0,"val":"assignments","end":""}],
    types: placeholder as Registry['assignments.update']['types'],
  },
  'assignments.destroy': {
    methods: ["DELETE"],
    pattern: '/v1/assignments',
    tokens: [{"old":"/v1/assignments","type":0,"val":"v1","end":""},{"old":"/v1/assignments","type":0,"val":"assignments","end":""}],
    types: placeholder as Registry['assignments.destroy']['types'],
  },
  'responses.index': {
    methods: ["GET","HEAD"],
    pattern: '/v1/responses',
    tokens: [{"old":"/v1/responses","type":0,"val":"v1","end":""},{"old":"/v1/responses","type":0,"val":"responses","end":""}],
    types: placeholder as Registry['responses.index']['types'],
  },
  'preferences.index': {
    methods: ["GET","HEAD"],
    pattern: '/v1/preferences',
    tokens: [{"old":"/v1/preferences","type":0,"val":"v1","end":""},{"old":"/v1/preferences","type":0,"val":"preferences","end":""}],
    types: placeholder as Registry['preferences.index']['types'],
  },
  'job_eligible_members.index': {
    methods: ["GET","HEAD"],
    pattern: '/v1/job-eligible-members',
    tokens: [{"old":"/v1/job-eligible-members","type":0,"val":"v1","end":""},{"old":"/v1/job-eligible-members","type":0,"val":"job-eligible-members","end":""}],
    types: placeholder as Registry['job_eligible_members.index']['types'],
  },
  'job_eligible_members.store': {
    methods: ["POST"],
    pattern: '/v1/job-eligible-members',
    tokens: [{"old":"/v1/job-eligible-members","type":0,"val":"v1","end":""},{"old":"/v1/job-eligible-members","type":0,"val":"job-eligible-members","end":""}],
    types: placeholder as Registry['job_eligible_members.store']['types'],
  },
  'job_eligible_members.destroy': {
    methods: ["DELETE"],
    pattern: '/v1/job-eligible-members',
    tokens: [{"old":"/v1/job-eligible-members","type":0,"val":"v1","end":""},{"old":"/v1/job-eligible-members","type":0,"val":"job-eligible-members","end":""}],
    types: placeholder as Registry['job_eligible_members.destroy']['types'],
  },
  'account_preferences.preferences.mine': {
    methods: ["GET","HEAD"],
    pattern: '/v1/account/preferences',
    tokens: [{"old":"/v1/account/preferences","type":0,"val":"v1","end":""},{"old":"/v1/account/preferences","type":0,"val":"account","end":""},{"old":"/v1/account/preferences","type":0,"val":"preferences","end":""}],
    types: placeholder as Registry['account_preferences.preferences.mine']['types'],
  },
  'account_preferences.preferences.update_mine': {
    methods: ["PUT","PATCH"],
    pattern: '/v1/account/preferences',
    tokens: [{"old":"/v1/account/preferences","type":0,"val":"v1","end":""},{"old":"/v1/account/preferences","type":0,"val":"account","end":""},{"old":"/v1/account/preferences","type":0,"val":"preferences","end":""}],
    types: placeholder as Registry['account_preferences.preferences.update_mine']['types'],
  },
  'fast_passes.index': {
    methods: ["GET","HEAD"],
    pattern: '/v1/fast-passes',
    tokens: [{"old":"/v1/fast-passes","type":0,"val":"v1","end":""},{"old":"/v1/fast-passes","type":0,"val":"fast-passes","end":""}],
    types: placeholder as Registry['fast_passes.index']['types'],
  },
  'fast_passes.store': {
    methods: ["POST"],
    pattern: '/v1/fast-passes',
    tokens: [{"old":"/v1/fast-passes","type":0,"val":"v1","end":""},{"old":"/v1/fast-passes","type":0,"val":"fast-passes","end":""}],
    types: placeholder as Registry['fast_passes.store']['types'],
  },
  'fast_passes.show': {
    methods: ["GET","HEAD"],
    pattern: '/v1/fast-passes/:id',
    tokens: [{"old":"/v1/fast-passes/:id","type":0,"val":"v1","end":""},{"old":"/v1/fast-passes/:id","type":0,"val":"fast-passes","end":""},{"old":"/v1/fast-passes/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['fast_passes.show']['types'],
  },
  'fast_passes.update': {
    methods: ["PUT"],
    pattern: '/v1/fast-passes/:id',
    tokens: [{"old":"/v1/fast-passes/:id","type":0,"val":"v1","end":""},{"old":"/v1/fast-passes/:id","type":0,"val":"fast-passes","end":""},{"old":"/v1/fast-passes/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['fast_passes.update']['types'],
  },
  'fast_passes.destroy': {
    methods: ["DELETE"],
    pattern: '/v1/fast-passes/:id',
    tokens: [{"old":"/v1/fast-passes/:id","type":0,"val":"v1","end":""},{"old":"/v1/fast-passes/:id","type":0,"val":"fast-passes","end":""},{"old":"/v1/fast-passes/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['fast_passes.destroy']['types'],
  },
  'transactions.index': {
    methods: ["GET","HEAD"],
    pattern: '/v1/transactions',
    tokens: [{"old":"/v1/transactions","type":0,"val":"v1","end":""},{"old":"/v1/transactions","type":0,"val":"transactions","end":""}],
    types: placeholder as Registry['transactions.index']['types'],
  },
  'vouchers.index': {
    methods: ["GET","HEAD"],
    pattern: '/v1/vouchers',
    tokens: [{"old":"/v1/vouchers","type":0,"val":"v1","end":""},{"old":"/v1/vouchers","type":0,"val":"vouchers","end":""}],
    types: placeholder as Registry['vouchers.index']['types'],
  },
  'vouchers.store': {
    methods: ["POST"],
    pattern: '/v1/vouchers',
    tokens: [{"old":"/v1/vouchers","type":0,"val":"v1","end":""},{"old":"/v1/vouchers","type":0,"val":"vouchers","end":""}],
    types: placeholder as Registry['vouchers.store']['types'],
  },
  'vouchers.update': {
    methods: ["PUT","PATCH"],
    pattern: '/v1/vouchers/:id',
    tokens: [{"old":"/v1/vouchers/:id","type":0,"val":"v1","end":""},{"old":"/v1/vouchers/:id","type":0,"val":"vouchers","end":""},{"old":"/v1/vouchers/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['vouchers.update']['types'],
  },
  'vouchers.destroy': {
    methods: ["DELETE"],
    pattern: '/v1/vouchers/:id',
    tokens: [{"old":"/v1/vouchers/:id","type":0,"val":"v1","end":""},{"old":"/v1/vouchers/:id","type":0,"val":"vouchers","end":""},{"old":"/v1/vouchers/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['vouchers.destroy']['types'],
  },
  'logs.index': {
    methods: ["GET","HEAD"],
    pattern: '/v1/logs',
    tokens: [{"old":"/v1/logs","type":0,"val":"v1","end":""},{"old":"/v1/logs","type":0,"val":"logs","end":""}],
    types: placeholder as Registry['logs.index']['types'],
  },
  'logs.store': {
    methods: ["POST"],
    pattern: '/v1/logs',
    tokens: [{"old":"/v1/logs","type":0,"val":"v1","end":""},{"old":"/v1/logs","type":0,"val":"logs","end":""}],
    types: placeholder as Registry['logs.store']['types'],
  },
  'logs.show': {
    methods: ["GET","HEAD"],
    pattern: '/v1/logs/:id',
    tokens: [{"old":"/v1/logs/:id","type":0,"val":"v1","end":""},{"old":"/v1/logs/:id","type":0,"val":"logs","end":""},{"old":"/v1/logs/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['logs.show']['types'],
  },
  'logs.update': {
    methods: ["PUT","PATCH"],
    pattern: '/v1/logs/:id',
    tokens: [{"old":"/v1/logs/:id","type":0,"val":"v1","end":""},{"old":"/v1/logs/:id","type":0,"val":"logs","end":""},{"old":"/v1/logs/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['logs.update']['types'],
  },
  'logs.destroy': {
    methods: ["DELETE"],
    pattern: '/v1/logs/:id',
    tokens: [{"old":"/v1/logs/:id","type":0,"val":"v1","end":""},{"old":"/v1/logs/:id","type":0,"val":"logs","end":""},{"old":"/v1/logs/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['logs.destroy']['types'],
  },
  'sessions.sessions.index': {
    methods: ["GET","HEAD"],
    pattern: '/v1/account/sessions',
    tokens: [{"old":"/v1/account/sessions","type":0,"val":"v1","end":""},{"old":"/v1/account/sessions","type":0,"val":"account","end":""},{"old":"/v1/account/sessions","type":0,"val":"sessions","end":""}],
    types: placeholder as Registry['sessions.sessions.index']['types'],
  },
  'sessions.sessions.destroy': {
    methods: ["DELETE"],
    pattern: '/v1/account/sessions/:id',
    tokens: [{"old":"/v1/account/sessions/:id","type":0,"val":"v1","end":""},{"old":"/v1/account/sessions/:id","type":0,"val":"account","end":""},{"old":"/v1/account/sessions/:id","type":0,"val":"sessions","end":""},{"old":"/v1/account/sessions/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['sessions.sessions.destroy']['types'],
  },
} as const satisfies Record<string, AdonisEndpoint>

export { routes }

export const registry = {
  routes,
  $tree: {} as ApiDefinition,
}

declare module '@tuyau/core/types' {
  export interface UserRegistry {
    routes: typeof routes
    $tree: ApiDefinition
  }
}
